version: '3.7'

services:
    nginx:
        image: nginx:1.17-alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www:cached
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - default

    mysql:
        image: mysql:5.7
        restart: unless-stopped
        tty: true
        ports:
            - "33061:3306"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - default

    php:
        build:
            context: ./docker/php
        volumes:
            - ./:/var/www:cached
            - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
            - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        ports:
            - "9000:9000"
        environment:
            DB_PORT: 3306
            DB_HOST: mysql
        networks:
            - default

networks:
    default:
        driver: bridge