version: '3.7'

services:
    nginx:
        image: nginx:1.17-alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www:cached
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
            - mysql-test

    mysql:
        image: mysql:5.7
        restart: unless-stopped
        tty: true
        ports:
            - "33061:3306"
        environment:
            MYSQL_DATABASE: nova3
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret

    mysql-test:
        image: mysql:5.7
        restart: unless-stopped
        tty: true
        ports:
            - "33062:3306"
        environment:
            MYSQL_DATABASE: nova3
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret

    php:
        build:
            context: ./
            dockerfile: docker/php.dockerfile
        volumes:
            - ./:/var/www:cached
            - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
            - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        ports:
            - "9000:9000"