<?php

declare(strict_types=1);

namespace Nova\Foundation\Icons;

class TablerIconSet extends IconSet
{
    public function icons(): array
    {
        return [
            'add' => 'tabler-square-rounded-plus',
            'alarm' => 'tabler-alarm',
            'alert' => 'tabler-alert-square-rounded',
            'arrow-down' => 'tabler-square-rounded-arrow-down',
            'arrow-left' => 'tabler-square-rounded-arrow-left',
            'arrow-right' => 'tabler-square-rounded-arrow-right',
            'arrow-up' => 'tabler-square-rounded-arrow-up',
            'arrows-sort' => 'tabler-arrows-sort',
            'arrows-sync' => 'tabler-refresh',
            'bell' => 'tabler-bell',
            'blockquote' => 'tabler-blockquote',
            'bolt' => 'tabler-bolt',
            'book' => 'tabler-notebook',
            'books' => 'tabler-books',
            'bookmark' => 'tabler-bookmark',
            'bulb' => 'tabler-bulb',
            'calendar' => 'tabler-calendar',
            'change' => 'tabler-arrows-exchange',
            'characters' => 'tabler-masks-theater',
            'chart' => 'tabler-chart-bar',
            'check' => 'tabler-square-rounded-check',
            'chevron-down' => 'tabler-chevron-down',
            'chevron-left' => 'tabler-chevron-left',
            'chevron-right' => 'tabler-chevron-right',
            'chevron-up' => 'tabler-chevron-up',
            'clipboard' => 'tabler-clipboard',
            'clock' => 'tabler-clock-hour-3',
            'clock-edit' => 'tabler-clock-edit',
            'cloud' => 'tabler-cloud',
            'code' => 'tabler-code',
            'columns' => 'tabler-columns-3',
            'copy' => 'tabler-copy',
            'dashboard' => 'tabler-gauge',
            'database' => 'tabler-database',
            'device-desktop' => 'tabler-device-desktop',
            'device-mobile' => 'tabler-device-mobile',
            'device-tablet' => 'tabler-device-tablet',
            'discord' => 'tabler-brand-discord',
            'dismiss' => 'tabler-square-rounded-x',
            'edit' => 'tabler-pencil',
            'edit-off' => 'tabler-pencil-off',
            'edit-settings' => 'tabler-pencil-cog',
            'enter' => 'tabler-door-enter',
            'exit' => 'tabler-door-exit',
            'explicit' => 'tabler-explicit',
            'filter' => 'tabler-filter',
            'flag' => 'tabler-flag',
            'folder' => 'tabler-folder',
            'forbid' => 'tabler-forbid-2',
            'form' => 'tabler-forms',
            'form-preview' => 'tabler-input-search',
            'globe' => 'tabler-world',
            'heart' => 'tabler-heart',
            'help' => 'tabler-help-square-rounded',
            'hide' => 'tabler-eye-off',
            'history' => 'tabler-history',
            'home' => 'tabler-home',
            'image' => 'tabler-photo-square-rounded',
            'info' => 'tabler-info-square-rounded',
            'key' => 'tabler-key',
            'layer' => 'tabler-stack-2',
            'leaf' => 'tabler-leaf',
            'link' => 'tabler-link',
            'list' => 'tabler-list',
            'location' => 'tabler-map-pin',
            'lock-check' => 'tabler-lock-check',
            'lock-closed' => 'tabler-lock',
            'lock-open' => 'tabler-lock-open',
            'lock-x' => 'tabler-lock-x',
            'login' => 'tabler-login',
            'logout' => 'tabler-logout',
            'mail' => 'tabler-mail',
            'mature' => 'tabler-rating-18-plus',
            'megaphone' => 'tabler-speakerphone',
            'menu' => 'tabler-menu-2',
            'messages' => 'tabler-messages',
            'moon' => 'tabler-moon-stars',
            'more' => 'tabler-dots-vertical',
            'move-down' => 'tabler-arrow-down-square',
            'move-right' => 'tabler-arrow-right-square',
            'move-up' => 'tabler-arrow-up-square',
            'note' => 'tabler-note',
            'notification' => 'tabler-notification',
            'notification-off' => 'tabler-notification-off',
            'number' => 'tabler-number-123',
            'paint-brush' => 'tabler-brush',
            'palette' => 'tabler-palette',
            'plus-minus' => 'tabler-plus-minus',
            'preferences' => 'tabler-adjustments',
            'prohibited' => 'tabler-ban',
            'rank' => 'tabler-military-rank',
            'remove' => 'tabler-square-rounded-minus',
            'rocket' => 'tabler-rocket',
            'search' => 'tabler-search',
            'send' => 'tabler-send',
            'server' => 'tabler-server',
            'settings' => 'tabler-settings',
            'share' => 'tabler-share-3',
            'shield' => 'tabler-shield',
            'show' => 'tabler-eye',
            'sort-ascending' => 'tabler-sort-ascending-2',
            'sort-descending' => 'tabler-sort-descending-2',
            'sparkles' => 'tabler-sparkles',
            'spy' => 'tabler-spy',
            'star' => 'tabler-star',
            'status-change' => 'tabler-status-change',
            'sun' => 'tabler-sun',
            'tag' => 'tabler-tag',
            'tags' => 'tabler-tags',
            'thumbs-down' => 'tabler-thumb-down',
            'thumbs-up' => 'tabler-thumb-up',
            'timeline' => 'tabler-timeline-event',
            'tool' => 'tabler-tool',
            'tools' => 'tabler-tools',
            'trash' => 'tabler-trash',
            'typography' => 'tabler-typography',
            'update' => 'tabler-refresh-dot',
            'update-alert' => 'tabler-refresh-alert',
            'user' => 'tabler-user',
            'user-profile' => 'tabler-user-circle',
            'user-scan' => 'tabler-user-scan',
            'users' => 'tabler-users',
            'wand' => 'tabler-wand',
            'warning' => 'tabler-alert-triangle',
            'write' => 'tabler-edit',
            'www' => 'tabler-world-www',
            'www-preview' => 'tabler-world-search',
            'x' => 'tabler-x',
        ];
    }

    public function name(): string
    {
        return 'Tabler';
    }

    public function prefix(): string
    {
        return 'tabler';
    }
}
