<?php

declare(strict_types=1);

namespace Nova\Foundation\Icons;

class TablerIconSet extends IconSet
{
    public function icons(): array
    {
        return [
            'abc' => 'tabler-abc',
            'activity' => 'tabler-activity',
            'add' => 'tabler-plus',
            'add-circle' => 'tabler-circle-plus',
            'alarm' => 'tabler-alarm',
            'alert' => 'tabler-exclamation-circle',
            'alert-filled' => 'tabler-exclamation-circle-filled',
            'alert-circle' => 'tabler-alert-circle',
            'arrow-down' => 'tabler-circle-arrow-down',
            'arrow-left' => 'tabler-circle-arrow-left',
            'arrow-right' => 'tabler-circle-arrow-right',
            'arrow-vertical-end' => 'tabler-arrow-bar-to-down',
            'arrow-vertical-start' => 'tabler-arrow-bar-to-up',
            'arrow-up' => 'tabler-circle-arrow-up',
            'arrows-sort' => 'tabler-arrows-sort',
            'arrows-sync' => 'tabler-refresh',
            'automation' => 'tabler-automation',
            'award' => 'tabler-award',
            'bell' => 'tabler-bell',
            'blockquote' => 'tabler-blockquote',
            'bolt' => 'tabler-bolt',
            'bolt-off' => 'tabler-bolt-off',
            'book' => 'tabler-notebook',
            'books' => 'tabler-books',
            'bookmark' => 'tabler-bookmark',
            'brand-discord' => 'tabler-brand-discord',
            'brand-php' => 'tabler-brand-php',
            'broadcast' => 'tabler-broadcast',
            'bulb' => 'tabler-bulb',
            'calendar' => 'tabler-calendar',
            'change' => 'tabler-arrows-exchange',
            'characters' => 'tabler-masks-theater',
            'chart' => 'tabler-chart-bar',
            'chart-dots' => 'tabler-chart-dots',
            'chart-histogram' => 'tabler-chart-histogram',
            'chart-infographic' => 'tabler-chart-infographic',
            'chart-line' => 'tabler-chart-line',
            'check' => 'tabler-circle-check',
            'check-circle' => 'tabler-circle-check',
            'check-circle-filled' => 'tabler-circle-check-filled',
            'checklist' => 'tabler-checklist',
            'checks' => 'tabler-checks',
            'chevron-down' => 'tabler-chevron-down',
            'chevron-left' => 'tabler-chevron-left',
            'chevron-right' => 'tabler-chevron-right',
            'chevron-up' => 'tabler-chevron-up',
            'circle-dashed' => 'tabler-circle-dashed',
            'clipboard' => 'tabler-clipboard',
            'clock' => 'tabler-clock-hour-3',
            'clock-edit' => 'tabler-clock-edit',
            'cloud' => 'tabler-cloud',
            'cloud-share' => 'tabler-cloud-share',
            'code' => 'tabler-code',
            'columns' => 'tabler-columns-3',
            'copy' => 'tabler-copy',
            'dashboard' => 'tabler-layout-dashboard',
            'database' => 'tabler-database',
            'database-export' => 'tabler-database-export',
            'database-import' => 'tabler-database-import',
            'database-off' => 'tabler-database-off',
            'database-settings' => 'tabler-database-cog',
            'database-smile' => 'tabler-database-smile',
            'device-desktop' => 'tabler-device-desktop',
            'device-mobile' => 'tabler-device-mobile',
            'device-tablet' => 'tabler-device-tablet',
            'device' => 'tabler-devices',
            'dismiss' => 'tabler-circle-x',
            'download' => 'tabler-cloud-download',
            'drag-handle' => 'tabler-grip-vertical',
            'edit' => 'tabler-pencil',
            'edit-off' => 'tabler-pencil-off',
            'edit-settings' => 'tabler-pencil-cog',
            'enter' => 'tabler-door-enter',
            'eraser' => 'tabler-eraser',
            'exit' => 'tabler-door-exit',
            'explicit' => 'tabler-explicit',
            'external' => 'tabler-external-link',
            'file' => 'tabler-file',
            'file-text' => 'tabler-file-text',
            'file-settings' => 'tabler-file-settings',
            'filter' => 'tabler-filter',
            'flag' => 'tabler-flag',
            'folder' => 'tabler-folder',
            'folder-settings' => 'tabler-folder-cog',
            'forbid' => 'tabler-forbid-2',
            'form' => 'tabler-forms',
            'form-preview' => 'tabler-input-search',
            'forward-all' => 'tabler-arrow-forward-up-double',
            'gauge' => 'tabler-gauge',
            'gavel' => 'tabler-gavel',
            'globe' => 'tabler-world',
            'group' => 'tabler-box-multiple',
            'hammer' => 'tabler-hammer',
            'hammer-off' => 'tabler-hammer-off',
            'heart' => 'tabler-heart',
            'help' => 'tabler-help-circle',
            'hide' => 'tabler-eye-off',
            'history' => 'tabler-history',
            'home' => 'tabler-home',
            'image' => 'tabler-photo',
            'image-add' => 'tabler-photo-plus',
            'image-alert' => 'tabler-photo-exclamation',
            'inbox' => 'tabler-inbox',
            'info' => 'tabler-info-circle',
            'info-circle' => 'tabler-info-circle',
            'key' => 'tabler-key',
            'layer' => 'tabler-stack-2',
            'leaf' => 'tabler-leaf',
            'link' => 'tabler-link',
            'list' => 'tabler-list',
            'list-details' => 'tabler-list-details',
            'location' => 'tabler-map-pin',
            'lock-check' => 'tabler-lock-check',
            'lock-closed' => 'tabler-lock',
            'lock-open' => 'tabler-lock-open',
            'lock-x' => 'tabler-lock-x',
            'login' => 'tabler-login',
            'logout' => 'tabler-logout',
            'mail' => 'tabler-mail',
            'mature' => 'tabler-rating-18-plus',
            'megaphone' => 'tabler-speakerphone',
            'menu' => 'tabler-menu-2',
            'message' => 'tabler-message',
            'message-dots' => 'tabler-message-dots',
            'message-off' => 'tabler-message-off',
            'message-reply' => 'tabler-message-reply',
            'messages' => 'tabler-messages',
            'moon' => 'tabler-moon-stars',
            'more' => 'tabler-dots-vertical',
            'move-down' => 'tabler-arrow-down-square',
            'move-right' => 'tabler-arrow-right-square',
            'move-up' => 'tabler-arrow-up-square',
            'note' => 'tabler-note',
            'notification' => 'tabler-notification',
            'notification-off' => 'tabler-notification-off',
            'number' => 'tabler-number-123',
            'paint-brush' => 'tabler-brush',
            'palette' => 'tabler-palette',
            'play' => 'tabler-player-play',
            'plug' => 'tabler-plug',
            'plug-connected' => 'tabler-plug-connected',
            'plug-disconnected' => 'tabler-plug-connected-x',
            'plus-minus' => 'tabler-plus-minus',
            'preferences' => 'tabler-adjustments',
            'progress' => 'tabler-progress',
            'progress-check' => 'tabler-progress-check',
            'progress-x' => 'tabler-progress-x',
            'prohibited' => 'tabler-ban',
            'puzzle' => 'tabler-puzzle',
            'rank' => 'tabler-military-rank',
            'remove' => 'tabler-circle-minus',
            'reply' => 'tabler-arrow-back-up',
            'rocket' => 'tabler-rocket',
            'search' => 'tabler-search',
            'send' => 'tabler-send',
            'seo' => 'tabler-seo',
            'server' => 'tabler-server',
            'server-settings' => 'tabler-server-cog',
            'settings' => 'tabler-settings',
            'settings-check' => 'tabler-settings-check',
            'share' => 'tabler-share-3',
            'shield' => 'tabler-shield',
            'shield-lock' => 'tabler-shield-lock',
            'show' => 'tabler-eye',
            'sort-ascending' => 'tabler-sort-ascending-2',
            'sort-descending' => 'tabler-sort-descending-2',
            'sparkles' => 'tabler-sparkles',
            'spy' => 'tabler-spy',
            'star' => 'tabler-star',
            'status-change' => 'tabler-status-change',
            'sun' => 'tabler-sun',
            'support' => 'tabler-lifebuoy',
            'tag' => 'tabler-tag',
            'tags' => 'tabler-tags',
            'thumbs-down' => 'tabler-thumb-down',
            'thumbs-up' => 'tabler-thumb-up',
            'timeline' => 'tabler-timeline-event',
            'tool' => 'tabler-tool',
            'tools' => 'tabler-tools',
            'trash' => 'tabler-trash',
            'trash-alt' => 'tabler-trash-x',
            'trash-off' => 'tabler-trash-off',
            'typography' => 'tabler-typography',
            'update' => 'tabler-refresh-dot',
            'update-alert' => 'tabler-refresh-alert',
            'upload' => 'tabler-cloud-upload',
            'user' => 'tabler-user',
            'user-add' => 'tabler-user-plus',
            'user-edit' => 'tabler-user-edit',
            'user-profile' => 'tabler-user-circle',
            'user-scan' => 'tabler-user-scan',
            'users' => 'tabler-users',
            'users-group' => 'tabler-users-group',
            'versions' => 'tabler-versions',
            'wand' => 'tabler-wand',
            'warning' => 'tabler-alert-triangle',
            'warning-filled' => 'tabler-alert-triangle-filled',
            'wrench' => 'tabler-tool',
            'write' => 'tabler-edit',
            'www' => 'tabler-world-www',
            'www-preview' => 'tabler-world-search',
            'x' => 'tabler-x',
            'x-circle' => 'tabler-circle-x',
        ];
    }

    public function name(): string
    {
        return 'Tabler';
    }

    public function prefix(): string
    {
        return 'tabler';
    }
}
