<?php

use Nova\Foundation\Themes\Theme as BaseTheme;

class Theme extends BaseTheme {

	public $iconTemplate = '<i class="entypo-%1$s %2$s"></i>';

	public function iconMap(): array
	{
		return [
			'add'				=> 'plus',
			'android'			=> 'google-play',
			'announcement'		=> 'megaphone',
			'apple'				=> 'app-store',
			'archive'			=> 'box',
			'arrow-down'		=> 'arrow-with-circle-down',
			'arrow-left'		=> 'arrow-with-circle-left',
			'arrow-right'		=> 'arrow-with-circle-right',
			'arrow-up'			=> 'arrow-with-circle-up',
			'ban'				=> 'block',
			'bell'				=> 'bell',
			'bell-outline'		=> 'bell',
			'bolt'				=> 'flash',
			'book'				=> 'book',
			'bookmark'			=> 'bookmark',
			'briefcase'			=> 'briefcase',
			'browser-chrome'	=> 'network',
			'browser-edge'		=> 'network',
			'browser-firefox'	=> 'network',
			'browser-ie'		=> 'network',
			'browser-safari'	=> 'network',
			'calendar'			=> 'calendar',
			'caret-down'		=> 'chevron-small-down',
			'caret-up'			=> 'chevron-small-up',
			'chart-area'		=> 'area-graph',
			'chart-bar'			=> 'bar-graph',
			'chart-line'		=> 'line-graph',
			'chart-pie'			=> 'pie-chart',
			'check'				=> 'check',
			'clock'				=> 'clock',
			'clone'				=> 'popup',
			'close'				=> 'cross',
			'cloud'				=> 'cloud',
			'cloud-download'	=> '',
			'cloud-upload'		=> 'upload-to-cloud',
			'code'				=> 'code',
			'comment'			=> 'message',
			'comments'			=> 'chat',
			'dashboard'			=> 'gauge',
			'delete'			=> 'trash',
			'device-desktop'	=> 'tv',
			'device-laptop'		=> 'laptop',
			'device-mobile'		=> 'mobile',
			'device-tablet'		=> 'tablet',
			'download'			=> 'download',
			'edit'				=> 'edit',
			'email'				=> 'mail',
			'hide'				=> 'eye-with-line',
			'face-frown'		=> 'emoji-sad',
			'face-meh'			=> 'emoji-neutral',
			'face-smile'		=> 'emoji-happy',
			'facebook'			=> 'facebook',
			'file'				=> 'news',
			'file-text'			=> 'news',
			'fire'				=> 'new',
			'flag'				=> 'flag',
			'folder'			=> 'folder',
			'folder-open'		=> 'folder',
			'forward'			=> 'forward',
			'gift'				=> 'shopping-bag',
			'google'			=> 'google',
			'heart'				=> 'heart',
			'heart-empty'		=> 'heart-outlined',
			'history'			=> 'back-in-time',
			'home'				=> 'home',
			'image'				=> 'image',
			'inbox'				=> 'archive',
			'info'				=> 'info-with-circle',
			'key'				=> 'key',
			'leaf'				=> 'leaf',
			'lightbulb'			=> 'light-bulb',
			'link'				=> 'link',
			'linux'				=> '',
			'list'				=> 'list',
			'lock'				=> 'lock',
			'magic'				=> 'feather',
			'map-marker'		=> 'location-pin',
			'map-signs'			=> 'address',
			'more-horizontal'	=> 'dots-three-horizontal',
			'more-vertical'		=> 'dots-three-vertical',
			'paint-brush'		=> 'round-brush',
			'paper-plane'		=> 'paper-plane',
			'paper-plane-alt'	=> 'paper-plane',
			'question'			=> 'help-with-circle',
			'refresh'			=> 'cycle',
			'reply'				=> 'reply',
			'reply-all'			=> 'reply-all',
			'search'			=> 'magnifying-glass',
			'share'				=> 'share',
			'shield'			=> 'shield',
			'setting'			=> 'cog',
			'settings'			=> 'cog',
			'settings-alt'		=> 'sound-mix',
			'show'				=> 'eye',
			'sign-in'			=> 'login',
			'sign-out'			=> 'log-out',
			'sort-alpha-asc'	=> 'funnel',
			'sort-alpha-desc'	=> 'funnel',
			'sort-amount-asc'	=> 'funnel',
			'sort-amount-desc'	=> 'funnel',
			'sort-numeric-asc'	=> 'funnel',
			'sort-numeric-desc'	=> 'funnel',
			'star'				=> 'star',
			'star-empty'		=> 'star-outlined',
			'support'			=> 'lifebuoy',
			'tag'				=> 'price-tag',
			'tags'				=> 'price-tag',
			'tasks'				=> 'add-to-list',
			'thumbs-down'		=> 'thumbs-down',
			'thumbs-up'			=> 'thumbs-up',
			'ticket'			=> 'ticket',
			'trophy'			=> 'trophy',
			'twitter'			=> 'twitter',
			'unlock'			=> 'lock-open',
			'upload'			=> 'upload',
			'user'				=> 'user',
			'user-card'			=> 'v-card',
			'user-circle'		=> 'user',
			'users'				=> 'users',
			'warning'			=> 'warning',
			'windows'			=> 'windows-store',
			'wrench'			=> 'tools',
		];
	}
}
