<?php namespace Nova\Core\Controllers\Base;

/**
 * All ajax controllers extend from this base controller. This class is 
 * responsible for doing the necessary setup for all ajax requests.
 *
 * DO NOT EDIT THIS FILE!
 *
 * @package		Nova
 * @subpackage	Core
 * @category	Controllers
 * @author		Anodyne Productions
 * @copyright	2013 Anodyne Productions
 */

use App;
use Config;
use Sentry;
use Request;
use Controller;

abstract class Ajax extends Controller {

	/**
	 * The request instance.
	 */
	protected $request;

	/**
	 * The current logged in user.
	 */
	protected $currentUser;

	public function __construct()
	{
		// Get the request instance
		$this->request = Request::instance();

		// Get the current user
		$this->currentUser = Sentry::getUser();
	}

	/**
	 * Resolve bindings out of the container.
	 *
	 * @param	string	$alias	The alias to resolve
	 * @return	object
	 */
	protected function resolveBinding($alias)
	{
		// Get the aliases
		$classes = Config::get('app.aliases');

		return App::make($classes[$alias]);
	}

}