<?php namespace Nova\Core\Controllers\Base;

/**
 * All ajax controllers extend from this base controller. This class is 
 * responsible for doing the necessary setup for all ajax requests.
 *
 * DO NOT EDIT THIS FILE!
 *
 * @package		Nova
 * @subpackage	Core
 * @category	Controllers
 * @author		Anodyne Productions
 * @copyright	2013 Anodyne Productions
 */

use Request;
use Controller;
use NovaAuthInterface;

abstract class Ajax extends Controller {

	/**
	 * The request instance.
	 */
	protected $request;

	/**
	 * The current logged in user.
	 */
	protected $currentUser;

	public function __construct(NovaAuthInterface $auth)
	{
		// Set the auth interface
		$this->auth = $auth;
		
		// Get the request instance
		$this->request = Request::instance();

		// Get the current user
		$this->currentUser = $this->auth->getUser();
	}

}