<?php namespace Nova\Api\V1;

/**
 * All API controllers in Nova extend from this base controller.
 *
 * DO NOT EDIT THIS FILE!
 *
 * @package		Nova
 * @subpackage	Api
 * @category	Controllers
 * @author		Anodyne Productions
 * @copyright	2013 Anodyne Productions
 */

use URL;
use Request;
use Controller;

abstract class Base extends Controller {

	/**
	 * An instance of the current request.
	 */
	protected $request;

	/**
	 * The API URL group.
	 */
	protected $url;

	/**
	 * The number of results per page.
	 */
	protected $resultsPerPage = 25;

	public function __construct()
	{
		$this->url		= URL::to("api/v1");
		$this->request	= Request::instance();
	}

	/**
	 * Format the validation errors into a string.
	 *
	 * @param	Validator	$validator	The validator object
	 * @return	string
	 */
	protected function formatValidationErrors($validator)
	{
		return implode(', ', $validator->messages()->all());
	}

}