<?php namespace Nova\Api\V1;

/**
 * All API controllers in Nova extend from this base controller.
 *
 * DO NOT EDIT THIS FILE!
 *
 * @package		Nova
 * @subpackage	Api
 * @category	Controller
 * @author		Anodyne Productions
 * @copyright	2013 Anodyne Productions
 */

use Request;
use Controller;

abstract class Base extends Controller {

	/**
	 * An instance of the current request.
	 */
	protected $request;

	public function __construct()
	{
		$this->request = Request::instance();
	}

}