<?php

use Nova\Foundation\Themes\Theme as BaseTheme;

class Theme extends BaseTheme {

	public function getIconMap(): array
	{
		return [
			'add'			=> 'plus2',
			'announcement'	=> 'bullhorn',
			'archive'		=> 'box',
			'arrow-back'	=> 'circle-left4',
			'arrow-down'	=> 'circle-down4',
			'arrow-forward'	=> 'circle-right4',
			'arrow-up'		=> 'circle-up4',
			'ban'			=> 'blocked',
			'bolt'			=> 'power2',
			'book'			=> 'book3',
			'bookmark'		=> 'bookmark2',
			'briefcase'		=> 'briefcase',
			'brush'			=> 'brush',
			'calendar'		=> 'calendar2',
			'chart-area'	=> 'stats-growth',
			'chart-bar'		=> 'stats-bars2',
			'chart-line'	=> 'stats-dots',
			'chart-pie'		=> 'pie-chart7',
			'check'			=> 'checkmark4',
			'clock'			=> 'clock3',
			'close'			=> 'cross2',
			'cloud'			=> 'cloud2',
			'cloud-download'=> 'cloud-download2',
			'cloud-upload'	=> 'cloud-upload2',
			'code'			=> 'embed2',
			'comment'		=> 'bubble',
			'comments'		=> 'bubbles2',
			'copy'			=> 'copy3',
			'cut'			=> 'scissors3',
			'dashboard'		=> 'meter3',
			'delete'		=> 'bin2',
			'desktop'		=> 'display',
			'directions'	=> 'direction',
			'download'		=> 'download5',
			'edit'			=> 'pencil',
			'email'			=> 'envelop3',
			'file'			=> 'file-empty',
			'fire'			=> 'fire',
			'flag'			=> 'flag5',
			'folder'		=> 'folder2',
			'folder-open'	=> 'folder-open',
			'forward'		=> 'forward',
			'frown'			=> 'sad',
			'gift'			=> 'gift2',
			'heart'			=> 'heart3',
			'heart-empty'	=> 'heart4',
			'history'		=> 'history',
			'home'			=> 'home2',
			'image'			=> 'image',
			'inbox'			=> 'drawer2',
			'info'			=> 'info2',
			'key'			=> 'key',
			'laptop'		=> 'laptop',
			'leaf'			=> 'leaf',
			'light'			=> 'lamp8',
			'link'			=> 'link',
			'list'			=> 'list2',
			'location'		=> 'location',
			'lock'			=> 'lock5',
			'mobile'		=> 'mobile',
			'more'			=> 'menu',
			'not-visible'	=> 'eye-blocked',
			'notifications'	=> 'bell2',
			'paste'			=> 'copy',
			'question'		=> 'question4',
			'refresh'		=> 'loop3',
			'reply'			=> 'reply',
			'reply-all'		=> 'reply-all',
			'search'		=> 'search3',
			'send'			=> 'paperplane',
			'settings'		=> 'cog2',
			'share'			=> 'share3',
			'shield'		=> 'shield',
			'sign-in'		=> 'enter',
			'sign-out'		=> 'exit',
			'smile'			=> 'happy',
			'star'			=> 'star-full2',
			'star-empty'	=> 'star-empty3',
			'tablet'		=> 'tablet',
			'tag'			=> 'price-tag2',
			'tasks'			=> 'import',
			'thumbs-down'	=> 'thumbs-down3',
			'thumbs-up'		=> 'thumbs-up3',
			'ticket'		=> 'ticket',
			'trophy'		=> 'trophy2',
			'unlock'		=> 'unlocked2',
			'upload'		=> 'upload5',
			'user'			=> 'user',
			'users'			=> 'users',
			'visible'		=> 'eye',
			'warning'		=> 'warning2',
			'wizard'		=> 'magic-wand',
			'wrench'		=> 'wrench',
		];
	}

	public function iconTemplate(): string
	{
		return '<i class="icomoon-%icon% %classes%"></i>';
	}

}
