<?php

declare(strict_types=1);

return [
    BladeUI\Icons\BladeIconsServiceProvider::class,
    Lab404\Impersonate\ImpersonateServiceProvider::class,
    LivewireUI\Spotlight\SpotlightServiceProvider::class,
    Livewire\LivewireServiceProvider::class,
    Nova\Addons\Providers\AddonServiceProvider::class,
    Nova\Announcements\Providers\AnnouncementServiceProvider::class,
    Nova\Applications\Providers\ApplicationServiceProvider::class,
    Nova\Characters\Providers\CharacterServiceProvider::class,
    Nova\Dashboards\Providers\DashboardsServiceProvider::class,
    Nova\Departments\Providers\DepartmentServiceProvider::class,
    Nova\Discussions\Providers\DiscussionServiceProvider::class,
    Nova\Forms\Providers\FormServiceProvider::class,
    Nova\Foundation\Providers\AppServiceProvider::class,
    Nova\Foundation\Providers\FortifyServiceProvider::class,
    Nova\Media\Providers\MediaServiceProvider::class,
    Nova\Menus\Providers\MenusServiceProvider::class,
    Nova\Notes\Providers\NotesServiceProvider::class,
    Nova\Pages\Providers\PageServiceProvider::class,
    Nova\PublicSite\Providers\PublicSiteServiceProvider::class,
    Nova\Ranks\Providers\RankServiceProvider::class,
    Nova\Reporting\Providers\ReportingServiceProvider::class,
    Nova\Roles\Providers\RoleServiceProvider::class,
    Nova\Search\Providers\SearchServiceProvider::class,
    Nova\Settings\Providers\SettingsServiceProvider::class,
    Nova\Setup\Providers\SetupServiceProvider::class,
    Nova\Stories\Providers\PostServiceProvider::class,
    Nova\Stories\Providers\PostTypeServiceProvider::class,
    Nova\Stories\Providers\StoryServiceProvider::class,
    Nova\Themes\Providers\ThemeServiceProvider::class,
    Nova\Users\Providers\UserServiceProvider::class,
];
