<?php
/**
 * Install Genre - DSV
 *
 * @package		Nova
 * @subpackage	Setup
 * @category	Asset
 * @author		Anodyne Productions
 * @copyright	2013 Anodyne Productions
 */
 
$g = 'dsv';

$data = array(
	'departments_'.$g 	=> 'depts',
	'ranks_info_'.$g	=> 'info',
	'ranks_groups_'.$g	=> 'groups',
	'ranks_'.$g			=> 'ranks',
	'positions_'.$g		=> 'positions',
	'catalog_ranks'		=> 'catalog_ranks',
);

$depts = array(
	array(
		'dept_name' => 'Command',
		'dept_desc' => "The Command Department consists of the Commanding Officer and the Executive Officer. The CO is ultimately responsible for the safety and welfare of the entire crew. S/he has final authority on all decisions regarding the ship and her mission. The XO is the CO's immediate subordinate, and is also his/her successor should the need arise. The Command Department is responsible for carrying out the orders of the UEO.",
		'dept_order' => 0,
		'dept_manifest' => 1),
	array(
		'dept_name' => 'Helm',
		'dept_desc' => "The Helm Department is responsible for the navigation and driving of the ship. In addition, the Helm Department can be called upon to drive the various mini-subs assigned to the ship as needed.",
		'dept_order' => 1,
		'dept_manifest' => 1),
	array(
		'dept_name' => 'Sonar',
		'dept_desc' => "The Sonar Department is responsible for all sonar equipment used aboard the ship, including the operation and maintenance of the ship's Wireless Sea Knowledge Retrieval Satellites (WSKRS).",
		'dept_order' => 2,
		'dept_manifest' => 1),
	array(
		'dept_name' => 'Communications',
		'dept_desc' => "The Communications Department is responsible for all communications in and out of the ship, including orders from UEO. In addition to standard communication channels, the Communications Department is responsible for the monitoring and use of military communication channels as well. In most cases, Communications Officers are multi-lingual in order to communicate with the various federations and factions throughout the world.",
		'dept_order' => 3,
		'dept_manifest' => 1),
	array(
		'dept_name' => 'EVA',
		'dept_desc' => "The EVA Department is responsible for all extra vehicular activities launched from the ship. This includes the control of all mini-subs assigned to the ship as well as any additional equipment for use outside of the ship. The EVA Department interfaces regularly with the Helm Department and works closely to train other members of the crew on safe EVA procedures as well as operation of the EVA equipment.",
		'dept_order' => 4,
		'dept_manifest' => 1),
	array(
		'dept_name' => 'Weapons',
		'dept_desc' => "The Weapons Department is responsible for all ordinance stored aboard the ship as well as the targeting and executing of ordiance release at the order of the Commanding Officer.",
		'dept_order' => 5,
		'dept_manifest' => 1),
	array(
		'dept_name' => 'Security',
		'dept_desc' => "The Security Department is responsible for the security aboard the ship as well as escorts for missions off the ship. Members of the Security Department are responsible for securing sensitive areas of the ship such as Engineering, Weapons Control, the Bridge and any other areas the Commanding Officer sees fit.",
		'dept_order' => 6,
		'dept_manifest' => 1),
	array(
		'dept_name' => 'Engineering',
		'dept_desc' => "The Engineering Department is responsible for the general upkeep and maintaince of the ship as well as any repairs that need to be done while the ship is at sea.",
		'dept_order' => 7,
		'dept_manifest' => 1),
	array(
		'dept_name' => 'Science/Medical',
		'dept_desc' => "While the UEO is a peacekeeping organization, one of its primary focuses is on exploration of the oceans. Nearly every UEO vessel has some sort of Science Department that is responsible for scientific experiments while the ship is at sea. The Science Department is also called on for their expertise with undersea topography and general scientific knowledge for the successful completion of many of the UEO's missions.",
		'dept_order' => 8,
		'dept_manifest' => 1),
	array(
		'dept_name' => 'Marine Detachment',
		'dept_desc' => "Despite being a peaceful organization, the UEO Marine Corps is responsible for both defensive and offensive missions at the orders of the UEO President. Because of hightening tensions between confederations, many UEO ships carry a Marine detachment for any type of missions that may require the additional muscle the Marine Corps brings with it.",
		'dept_order' => 9,
		'dept_manifest' => 1),
	array(
		'dept_name' => 'Support',
		'dept_desc' => "One of the most overlooked departments on UEO vessels, the Support department is responsible for supporting the crew and crew systems while the vessel is at sea.",
		'dept_order' => 10,
		'dept_manifest' => 1),
);

$groups = array(
	array('name' => 'Naval Admiralty', 'order' => 0),
	array('name' => 'Army Admiralty', 'order' => 1),
	array('name' => 'Command', 'order' => 2),
	array('name' => 'Support', 'order' => 3),
	array('name' => 'Medical and Sciences', 'order' => 4),
	array('name' => 'Army', 'order' => 5),
);

$info = array(
	array('name' => "Admiral", 'short_name' => "ADM", 'order' => 0, 'group' => 1),
	array('name' => "Vice-Admiral", 'short_name' => "VADM", 'order' => 1, 'group' => 1),
	array('name' => "Rear-Admiral", 'short_name' => "RADM", 'order' => 2, 'group' => 1),

	array('name' => "General", 'short_name' => "GEN", 'order' => 0, 'group' => 2),
	array('name' => "Major General", 'short_name' => "MAJ GEN", 'order' => 1, 'group' => 2),
	array('name' => "Brigadier General", 'short_name' => "BRG GEN", 'order' => 2, 'group' => 2),

	array('name' => "Captain", 'short_name' => "CAPT", 'order' => 0, 'group' => 3),
	array('name' => "Commander", 'short_name' => "CMDR", 'order' => 1, 'group' => 3),
	array('name' => "Lieutenant Commander", 'short_name' => "LT CMDR", 'order' => 2, 'group' => 3),
	array('name' => "Lieutenant", 'short_name' => "LT", 'order' => 3, 'group' => 3),
	array('name' => "Lieutenant JG", 'short_name' => "LT(JG)", 'order' => 4, 'group' => 3),
	array('name' => "Ensign", 'short_name' => "ENS", 'order' => 5, 'group' => 3),

	array('name' => "Colonel", 'short_name' => "COL", 'order' => 0, 'group' => 4),
	array('name' => "Lieutenant Colonel", 'short_name' => "LT COL", 'order' => 1, 'group' => 4),
	array('name' => "Major", 'short_name' => "MAJ", 'order' => 2, 'group' => 4),
	array('name' => "Captain", 'short_name' => "CAPT", 'order' => 3, 'group' => 4),
	array('name' => "1st Lieutenant", 'short_name' => "1LT", 'order' => 4, 'group' => 4),
	array('name' => "2nd Lieutenant", 'short_name' => "2LT", 'order' => 5, 'group' => 4),

	array('name' => "Chief Warrant Officer 3", 'short_name' => "CWO3", 'order' => 0, 'group' => 5),
	array('name' => "Chief Warrant Officer 2", 'short_name' => "CWO2", 'order' => 1, 'group' => 5),
	array('name' => "Warrant Officer", 'short_name' => "WO", 'order' => 2, 'group' => 5),

	array('name' => "Master Chief Petty Officer", 'short_name' => "MCPO", 'order' => 0, 'group' => 6),
	array('name' => "Senior Chief Petty Officer", 'short_name' => "SCPO", 'order' => 1, 'group' => 6),
	array('name' => "Chief Petty Officer", 'short_name' => "CPO", 'order' => 2, 'group' => 6),
	array('name' => "Petty Officer 1st Class", 'short_name' => "PO1", 'order' => 3, 'group' => 6),
	array('name' => "Petty Officer 2nd Class", 'short_name' => "PO2", 'order' => 4, 'group' => 6),
	array('name' => "Petty Officer 3rd Class", 'short_name' => "PO3", 'order' => 5, 'group' => 6),
	array('name' => "Seaman", 'short_name' => "SEA", 'order' => 3, 'group' => 6),
	array('name' => "Seaman Apprentice", 'short_name' => "SAPP", 'order' => 4, 'group' => 6),
	array('name' => "Seaman Recruit", 'short_name' => "SREC", 'order' => 5, 'group' => 6),

	array('name' => "Sergeant Major", 'short_name' => "SMAJ", 'order' => 0, 'group' => 7),
	array('name' => "Master Sergeant", 'short_name' => "MSGT", 'order' => 1, 'group' => 7),
	array('name' => "Gunnery Sergeant", 'short_name' => "GSGT", 'order' => 2, 'group' => 7),
	array('name' => "Staff Sergeant", 'short_name' => "SSGT", 'order' => 3, 'group' => 7),
	array('name' => "Sergeant", 'short_name' => "SGT", 'order' => 4, 'group' => 7),
	array('name' => "Corporal", 'short_name' => "CPL", 'order' => 5, 'group' => 7),
	array('name' => "Lance Corporal", 'short_name' => "LCPL", 'order' => 3, 'group' => 7),
	array('name' => "Private 1st Class", 'short_name' => "PVT1", 'order' => 4, 'group' => 7),
	array('name' => "Private", 'short_name' => "PVT", 'order' => 5, 'group' => 7),
);

$ranks = array(
	array('info_id' => 1, 'group_id' => 1, 'base' => 'yellow', 'pip' => 'a3'),
	array('info_id' => 2, 'group_id' => 1, 'base' => 'yellow', 'pip' => 'a2'),
	array('info_id' => 3, 'group_id' => 1, 'base' => 'yellow', 'pip' => 'a1'),

	array('info_id' => 4, 'group_id' => 2, 'base' => 'gray', 'pip' => 'a3'),
	array('info_id' => 5, 'group_id' => 2, 'base' => 'gray', 'pip' => 'a2'),
	array('info_id' => 6, 'group_id' => 2, 'base' => 'gray', 'pip' => 'a1'),

	array('info_id' => 7, 'group_id' => 3, 'base' => 'blue', 'pip' => 'o6'),
	array('info_id' => 8, 'group_id' => 3, 'base' => 'blue', 'pip' => 'o5'),
	array('info_id' => 9, 'group_id' => 3, 'base' => 'blue', 'pip' => 'o4'),
	array('info_id' => 10, 'group_id' => 3, 'base' => 'blue', 'pip' => 'o3'),
	array('info_id' => 11, 'group_id' => 3, 'base' => 'blue', 'pip' => 'o2'),
	array('info_id' => 12, 'group_id' => 3, 'base' => 'blue', 'pip' => 'o1'),
	array('info_id' => 19, 'group_id' => 3, 'base' => 'blue', 'pip' => 'w3'),
	array('info_id' => 20, 'group_id' => 3, 'base' => 'blue', 'pip' => 'w2'),
	array('info_id' => 21, 'group_id' => 3, 'base' => 'blue', 'pip' => 'w1'),
	array('info_id' => 22, 'group_id' => 3, 'base' => 'blue', 'pip' => 'e9'),
	array('info_id' => 23, 'group_id' => 3, 'base' => 'blue', 'pip' => 'e8'),
	array('info_id' => 24, 'group_id' => 3, 'base' => 'blue', 'pip' => 'e7'),
	array('info_id' => 25, 'group_id' => 3, 'base' => 'blue', 'pip' => 'e6'),
	array('info_id' => 26, 'group_id' => 3, 'base' => 'blue', 'pip' => 'e5'),
	array('info_id' => 27, 'group_id' => 3, 'base' => 'blue', 'pip' => 'e4'),
	array('info_id' => 28, 'group_id' => 3, 'base' => 'blue', 'pip' => 'e3'),
	array('info_id' => 29, 'group_id' => 3, 'base' => 'blue', 'pip' => 'e2'),
	array('info_id' => 30, 'group_id' => 3, 'base' => 'blue', 'pip' => 'e1'),

	array('info_id' => 7, 'group_id' => 4, 'base' => 'red', 'pip' => 'o6'),
	array('info_id' => 8, 'group_id' => 4, 'base' => 'red', 'pip' => 'o5'),
	array('info_id' => 9, 'group_id' => 4, 'base' => 'red', 'pip' => 'o4'),
	array('info_id' => 10, 'group_id' => 4, 'base' => 'red', 'pip' => 'o3'),
	array('info_id' => 11, 'group_id' => 4, 'base' => 'red', 'pip' => 'o2'),
	array('info_id' => 12, 'group_id' => 4, 'base' => 'red', 'pip' => 'o1'),
	array('info_id' => 19, 'group_id' => 4, 'base' => 'red', 'pip' => 'w3'),
	array('info_id' => 20, 'group_id' => 4, 'base' => 'red', 'pip' => 'w2'),
	array('info_id' => 21, 'group_id' => 4, 'base' => 'red', 'pip' => 'w1'),
	array('info_id' => 22, 'group_id' => 4, 'base' => 'red', 'pip' => 'e9'),
	array('info_id' => 23, 'group_id' => 4, 'base' => 'red', 'pip' => 'e8'),
	array('info_id' => 24, 'group_id' => 4, 'base' => 'red', 'pip' => 'e7'),
	array('info_id' => 25, 'group_id' => 4, 'base' => 'red', 'pip' => 'e6'),
	array('info_id' => 26, 'group_id' => 4, 'base' => 'red', 'pip' => 'e5'),
	array('info_id' => 27, 'group_id' => 4, 'base' => 'red', 'pip' => 'e4'),
	array('info_id' => 28, 'group_id' => 4, 'base' => 'red', 'pip' => 'e3'),
	array('info_id' => 29, 'group_id' => 4, 'base' => 'red', 'pip' => 'e2'),
	array('info_id' => 30, 'group_id' => 4, 'base' => 'red', 'pip' => 'e1'),

	array('info_id' => 7, 'group_id' => 5, 'base' => 'white', 'pip' => 'o6'),
	array('info_id' => 8, 'group_id' => 5, 'base' => 'white', 'pip' => 'o5'),
	array('info_id' => 9, 'group_id' => 5, 'base' => 'white', 'pip' => 'o4'),
	array('info_id' => 10, 'group_id' => 5, 'base' => 'white', 'pip' => 'o3'),
	array('info_id' => 11, 'group_id' => 5, 'base' => 'white', 'pip' => 'o2'),
	array('info_id' => 12, 'group_id' => 5, 'base' => 'white', 'pip' => 'o1'),
	array('info_id' => 19, 'group_id' => 5, 'base' => 'white', 'pip' => 'w3'),
	array('info_id' => 20, 'group_id' => 5, 'base' => 'white', 'pip' => 'w2'),
	array('info_id' => 21, 'group_id' => 5, 'base' => 'white', 'pip' => 'w1'),
	array('info_id' => 22, 'group_id' => 5, 'base' => 'white', 'pip' => 'e9'),
	array('info_id' => 23, 'group_id' => 5, 'base' => 'white', 'pip' => 'e8'),
	array('info_id' => 24, 'group_id' => 5, 'base' => 'white', 'pip' => 'e7'),
	array('info_id' => 25, 'group_id' => 5, 'base' => 'white', 'pip' => 'e6'),
	array('info_id' => 26, 'group_id' => 5, 'base' => 'white', 'pip' => 'e5'),
	array('info_id' => 27, 'group_id' => 5, 'base' => 'white', 'pip' => 'e4'),
	array('info_id' => 28, 'group_id' => 5, 'base' => 'white', 'pip' => 'e3'),
	array('info_id' => 29, 'group_id' => 5, 'base' => 'white', 'pip' => 'e2'),
	array('info_id' => 30, 'group_id' => 5, 'base' => 'white', 'pip' => 'e1'),

	array('info_id' => 13, 'group_id' => 6, 'base' => 'gray', 'pip' => 'o6'),
	array('info_id' => 14, 'group_id' => 6, 'base' => 'gray', 'pip' => 'o5'),
	array('info_id' => 15, 'group_id' => 6, 'base' => 'gray', 'pip' => 'o4'),
	array('info_id' => 16, 'group_id' => 6, 'base' => 'gray', 'pip' => 'o3'),
	array('info_id' => 17, 'group_id' => 6, 'base' => 'gray', 'pip' => 'o2'),
	array('info_id' => 18, 'group_id' => 6, 'base' => 'gray', 'pip' => 'o1'),
	array('info_id' => 19, 'group_id' => 6, 'base' => 'gray', 'pip' => 'w3'),
	array('info_id' => 20, 'group_id' => 6, 'base' => 'gray', 'pip' => 'w2'),
	array('info_id' => 21, 'group_id' => 6, 'base' => 'gray', 'pip' => 'w1'),
	array('info_id' => 31, 'group_id' => 6, 'base' => 'gray', 'pip' => 'e9'),
	array('info_id' => 32, 'group_id' => 6, 'base' => 'gray', 'pip' => 'e8'),
	array('info_id' => 33, 'group_id' => 6, 'base' => 'gray', 'pip' => 'e7'),
	array('info_id' => 34, 'group_id' => 6, 'base' => 'gray', 'pip' => 'e6'),
	array('info_id' => 35, 'group_id' => 6, 'base' => 'gray', 'pip' => 'e5'),
	array('info_id' => 36, 'group_id' => 6, 'base' => 'gray', 'pip' => 'e4'),
	array('info_id' => 37, 'group_id' => 6, 'base' => 'gray', 'pip' => 'e3'),
	array('info_id' => 38, 'group_id' => 6, 'base' => 'gray', 'pip' => 'e2'),
	array('info_id' => 39, 'group_id' => 6, 'base' => 'gray', 'pip' => 'e1'),
);

$positions = array(
	array(
		'pos_name' => 'Commanding Officer',
		'pos_desc' => "Ultimately responsible for the ship and crew, the Commanding Officer is the most senior officer aboard a vessel. S/he is responsible for carrying out the orders of the President and for representing the UEO. While their official title of the commander of a ship, they are usually referred to as \"the Captain\" regardless of their actual rank, or informally referred to as \"Skipper\".",
		'pos_dept' => 1,
		'pos_order' => 0,
		'pos_open' => 1,
		'pos_type' => 'senior'),
	array(
		'pos_name' => 'Executive Officer',
		'pos_desc' => "The liaison between captain and crew, the Executive Officer acts as the disciplinarian, personnel manager, advisor to the captain, and much more. S/he is also one of only two officers, along with the Chief Medical Officer, that can remove a Commanding Officer from duty.",
		'pos_dept' => 1,
		'pos_order' => 1,
		'pos_open' => 1,
		'pos_type' => 'senior'),
	array(
		'pos_name' => 'Chief of the Boat',
		'pos_desc' => "Usually the senior enlisted sailor aboard a submarine, the Chief of the Boat is an enlisted sailor who serves as the senior enlisted advisor to the Commanding Officer and Executive Officer, and assists with matters regarding the good order and discipline of the crew. The Chief of the Boat is generally responsible for the day-to-day operations of the non-engineering portion of the ship, the morale and the training of the boat's enlisted personnel.",
		'pos_dept' => 1,
		'pos_order' => 2,
		'pos_open' => 1,
		'pos_type' => 'enlisted'),
	array(
		'pos_name' => 'Yeoman',
		'pos_desc' => "The yeoman is a secretarial, clerical or payroll position responsible for administrative duties and reports to the Commanding Officer to aid him/her in their day-to-day duties.",
		'pos_dept' => 1,
		'pos_order' => 3,
		'pos_open' => 1,
		'pos_type' => 'enlisted'),
	array(
		'pos_name' => 'Chief Helmsman',
		'pos_desc' => "The Chief Helmsman is the seniormost officer in the Helm Department and is responsible for all navigation aboard the ship. Standing watch on the Bridge at least one shift a day, the Helmsman coordinates with navigators and drivers to move the vessel at the orders of the Commanding and Executive Officers.",
		'pos_dept' => 2,
		'pos_order' => 0,
		'pos_open' => 1,
		'pos_type' => 'senior'),
	array(
		'pos_name' => 'Helmsman',
		'pos_desc' => "Helmsmen aboard UEO vessels are responsible for coordination between the navigators and drivers for moving the vessel at the orders of the Commanding and Executive Officers. Expert drivers or navigators themselves, helmsmen will often take the reins of the ship in difficult situations that require more expertise.",
		'pos_dept' => 2,
		'pos_order' => 1,
		'pos_open' => 5,
		'pos_type' => 'officer'),
	array(
		'pos_name' => 'Navigator',
		'pos_desc' => "Navigators aboard UEO vessels are responsible for understanding undersea topography and safely navigating around underwater mountain ranges and other potentially hazardous areas of the oceans. Navigators must be oceanographic experts and thorough understand the use (and dangers) of thermal layers in the ocean as well as any other potential dangers in order to safely navigate the ship to where the Commanding and Executive Officers order.",
		'pos_dept' => 2,
		'pos_order' => 2,
		'pos_open' => 5,
		'pos_type' => 'officer'),
	array(
		'pos_name' => 'Driver',
		'pos_desc' => "Responsible for executing the orders of the helmsmen, sub drivers are the 'feet on the pedals' of the ship. Sub drivers are traditionally enlisted officers working their way toward a navigator or helmsman position. Because of the advanced nature of sub driving, these enlisted sailors are required to constantly undergo re-certification for their job.",
		'pos_dept' => 2,
		'pos_order' => 2,
		'pos_open' => 15,
		'pos_type' => 'enlisted'),
	array(
		'pos_name' => 'Mini-Sub Driver',
		'pos_desc' => "Often fresh out of training school, mini-sub drivers are sub drivers in training and gain further training through driver the various mini-subs assigned to the ship. It is not uncommon for mini-sub drivers to be given opportunities to drive the ship at the discretion of the Chief Helmsman as they continue their training and certification.",
		'pos_dept' => 2,
		'pos_order' => 2,
		'pos_open' => 5,
		'pos_type' => 'enlisted'),
	array(
		'pos_name' => 'Chief Sonar Officer',
		'pos_desc' => "The Chief Sonar Officer, also known as the Sensor Chief, is the seniormost Sonar officer aboard the ship and is responsible for the operation of all sonar equipment aboard the ship, including expert knowledge of the UEO's Wireless Sea Knowledge Retrieval Satellites (WSKRS) that are deployed on a wide variety of UEO vessels to date.",
		'pos_dept' => 3,
		'pos_order' => 0,
		'pos_open' => 1,
		'pos_type' => 'senior'),
	array(
		'pos_name' => 'Sonar Technician',
		'pos_desc' => "Sonar Technicians are responsible for the operation and maintenance of sonar systems aboard the ship under the direction of the Chief Sonar Officer.",
		'pos_dept' => 3,
		'pos_order' => 1,
		'pos_open' => 10,
		'pos_type' => 'enlisted'),
	array(
		'pos_name' => 'Chief Communications Officer',
		'pos_desc' => "The Chief Communications Officer is the head of the Communications Department and is responsible for all communication systems on the ship. In addition to standard communication channels and protocol, the Chief Communications Officer must also monitor and use military communication channels. Out of everyone in the Communications Department, the Chief needs to be multi-lingual to help in communicating with other confederations.",
		'pos_dept' => 4,
		'pos_order' => 0,
		'pos_open' => 1,
		'pos_type' => 'senior'),
	array(
		'pos_name' => 'Communications Officer',
		'pos_desc' => "Like the head of the department, a Communication Officer works with the Chief to keep all the communication systems on the ship running in top form. While usually multi-lingual, a Communication Officer rarely has the profiency with languages the Chief does. Like other positions in the UEO, a Communication Officer must constantly undergo certification training as well as additional language training.",
		'pos_dept' => 4,
		'pos_order' => 1,
		'pos_open' => 5,
		'pos_type' => 'officer'),
	array(
		'pos_name' => 'Chief EVA Officer',
		'pos_desc' => "The Chief EVA Officer is responsible for all extra vehicular activity that goes on outside of the ship. This often includes working with the Helm department to coordinate mini-sub missions, oversight of the launch bay and use of any other EVA equipment. In addition, the Chief EVA Officer is responsible for the safe execution of all EVA missions from the ship. The Chief EVA Officer must be certified in the use of all EVA equipment aboard the ship and routinely trains the crew and other EVA department personnel on the EVA equipment.",
		'pos_dept' => 5,
		'pos_order' => 0,
		'pos_open' => 1,
		'pos_type' => 'senior'),
	array(
		'pos_name' => 'EVA Operator',
		'pos_desc' => "EVA Operators are responsible for operating much of the EVA equipment aboard the ship. While the Helm department handles driving mini-subs most of the time, the EVA Operators are also capable of piloting the craft. In most cases, the EVA Operators only have general certification on the equipment and must defer to the Chief EVA Officer or EVA Equipment Specialists for more specialized knowledge.",
		'pos_dept' => 5,
		'pos_order' => 1,
		'pos_open' => 5,
		'pos_type' => 'officer'),
	array(
		'pos_name' => 'EVA Equipment Specialist',
		'pos_desc' => "EVA Equipment Specialists are highly trained operators of specific EVA equipment. In most cases, vessels will carry a few EVA specialists and bring additional specialists aboard as new equipment is added.",
		'pos_dept' => 5,
		'pos_order' => 2,
		'pos_open' => 5,
		'pos_type' => 'enlisted'),
	array(
		'pos_name' => 'Chief Weapons Officer',
		'pos_desc' => "The Chief Weapons Officer is responsible for the storage and release of all ordinance stored on the vessel. The Chief Weapons Officer interfaces with the Sonar department in tactical situations to establish firing solutions and provide the Commanding Officer as many tactical options as possible. Like other positions on the vessel, the Chief Weapons Officer must constantly be certifying and drilling for tactical situations that may arise.",
		'pos_dept' => 6,
		'pos_order' => 0,
		'pos_open' => 1,
		'pos_type' => 'senior'),
	array(
		'pos_name' => 'Fire Control Technician',
		'pos_desc' => "UEO Fire Control Technicians report to the Chief Weapons Officer and assist in the storage and release of the ordinance stored on the vessel. While not having the breadth of knowledge the Chief Weapons Officer has, technicians tend to specialize in one type of weapon and work toward additional certifications while on tour.",
		'pos_dept' => 6,
		'pos_order' => 1,
		'pos_open' => 5,
		'pos_type' => 'officer'),
	array(
		'pos_name' => 'Missile Technician',
		'pos_desc' => "Missile Technicians are highly trained specialized technicians with knowledge in the storage, targeting and release of missiles that have both nuclear and non-nuclear capabilities.",
		'pos_dept' => 6,
		'pos_order' => 2,
		'pos_open' => 2,
		'pos_type' => 'officer'),
	array(
		'pos_name' => 'Chief Security Officer',
		'pos_desc' => "The Chief Security Officer is responsible for all security aboard the vessel including the safe-keeping of ordinance, weapons and personnel. In the event an away team is sent from the vessel to land or another vessel or facility, the team will often consist of several members of the Security department, usually hand-picked by the Chief Security Officer. It is not uncommon for the Chief Security Officer to be from the enlisted ranks.",
		'pos_dept' => 7,
		'pos_order' => 0,
		'pos_open' => 1,
		'pos_type' => 'senior'),
	array(
		'pos_name' => 'Security Officer',
		'pos_desc' => "Reporting to the Chief Security Officer, UEO Security Officers help with all security aboard the vessel and will, at the selection of the Chief Security Officer, escort vessel personnel on missions off the vessel. Unlike most departments on the vessel, Security Officers are most often from the enlisted ranks.",
		'pos_dept' => 7,
		'pos_order' => 1,
		'pos_open' => 20,
		'pos_type' => 'enlisted'),
	array(
		'pos_name' => 'Master-At-Arms',
		'pos_desc' => "The Master-at-Arms is a non-commissioned officer responsible for training security personnel aboard UEO vessels as well as discipline and law enforcement aboard the vessel. The Master-at-Arms works closely with the Chief Security Officer and ultimately reports to them.",
		'pos_dept' => 7,
		'pos_order' => 2,
		'pos_open' => 1,
		'pos_type' => 'enlisted'),
	array(
		'pos_name' => 'Chief Engineer',
		'pos_desc' => "The Chief Engineer is responsible for the condition of all systems and equipment on board a UEO vessel. S/he oversees maintenance, repairs and upgrades of all equipment. S/he is also responsible for the many repairs teams during crisis situations. The Chief Engineer is not only the department head but also a senior officer, responsible for all the crew members in her/his department and maintenance of the duty rosters.",
		'pos_dept' => 8,
		'pos_order' => 0,
		'pos_open' => 1,
		'pos_type' => 'senior'),
	array(
		'pos_name' => 'Assistant Chief Engineer',
		'pos_desc' => "The Assistant Chief Engineer is the Chief Engineer's right-hand man and often knows just as much about the vessel as the Chief Engineer. When the Chief Engineer isn't available or is engaged in other work, the Assistant Chief Engineer does the same type of work the Chief Engineer does.",
		'pos_dept' => 8,
		'pos_order' => 1,
		'pos_open' => 1,
		'pos_type' => 'officer'),
	array(
		'pos_name' => 'Engineer',
		'pos_desc' => "There are several non-specialized engineers aboard of each vessel. They are assigned to their duties by the Chief Engineer, performing a number of different tasks as required, i.e. general maintenance and repair.",
		'pos_dept' => 8,
		'pos_order' => 2,
		'pos_open' => 10,
		'pos_type' => 'enlisted'),
	array(
		'pos_name' => 'Electronics Technician',
		'pos_desc' => "UEO vessels are complicated machines and one of the most important engineering technicians is the Electronics Technician. The Electronics Technicians are trained in the maintenance and report of any and all electrical systems aboard UEO vessels.",
		'pos_dept' => 8,
		'pos_order' => 3,
		'pos_open' => 4,
		'pos_type' => 'enlisted'),
	array(
		'pos_name' => 'Machinist',
		'pos_desc' => "When vessels are out at sea, there's often no time to stop at a base to pick up parts. A machinist is trained in the maintenance and fabrication of parts that may be necessary when out at sea. Some things cannot be fabricated on the vessel, but those components that can be fall under the jurisdiction of the machinists.",
		'pos_dept' => 8,
		'pos_order' => 4,
		'pos_open' => 2,
		'pos_type' => 'enlisted'),
	array(
		'pos_name' => 'Propulsion Technician',
		'pos_desc' => "As the UEO expands its operations, faster and more efficient propulsions systems are necessary. With more advanced propulsion systems come more to do with the maintenance and repair of those systems. Propulsion Technicians are specialized engineers who are trained in the propulsion systems used by the UEO.",
		'pos_dept' => 8,
		'pos_order' => 5,
		'pos_open' => 2,
		'pos_type' => 'enlisted'),
	array(
		'pos_name' => 'Chief Medical/Science Officer',
		'pos_desc' => "The Chief Medical/Science Officer is responsible for both the physical health of the entire crew as well as all Science operations aboard the vessel. The Chief Medical/Science Officer often has to contend with the military for resources on the vessel, though ultimately is one of the most important positions due to the UEO's committment to scientific research.",
		'pos_dept' => 9,
		'pos_order' => 0,
		'pos_open' => 1,
		'pos_type' => 'senior'),
	array(
		'pos_name' => 'Medical Officer',
		'pos_desc' => "Medical Officers undertake the majority of the work aboard the vessel, examining the crew, and administering medical care under the instruction of the Chief Medical/Science Officer. Medical Officers also run the other Medical areas not directly overseen by the Chief Medical Officer.",
		'pos_dept' => 9,
		'pos_order' => 1,
		'pos_open' => 2,
		'pos_type' => 'officer'),
	array(
		'pos_name' => 'Science Officer',
		'pos_desc' => "Science Officers undertake the majority of the scientific work aboard the vessel, studying samples and running experiments under the instruction of the Chief Medical/Science Officer. Science Officers also run their own experiments and projects based on their specialization and the vessel they are assigned to.",
		'pos_dept' => 9,
		'pos_order' => 2,
		'pos_open' => 8,
		'pos_type' => 'officer'),
	array(
		'pos_name' => 'Nurse',
		'pos_desc' => "S/he is responsible for providing first aid and trauma care with the help of the Medical Officers.",
		'pos_dept' => 9,
		'pos_order' => 2,
		'pos_open' => 3,
		'pos_type' => 'enlisted'),
	array(
		'pos_name' => 'Platoon Commander',
		'pos_desc' => "Most UEO combat-capable vessels carry a platoon (roughly 40 Marines) from the UEO Marine Corps. The Platoon Commander is responsible for all Marines aboard the vessel and coordinating with the various departments to ensure any operations that involve Marines happens smoothly and without incident.",
		'pos_dept' => 10,
		'pos_order' => 0,
		'pos_open' => 1,
		'pos_type' => 'senior'),
	array(
		'pos_name' => 'Platoon Sergeant',
		'pos_desc' => "Second in command to the Platoon Commander, the Platoon Sergeant is the seniormost enlisted Marine aboard a UEO combat-capable vessel and works with the Platoon Commander to manage the Marines aboard the vessel.",
		'pos_dept' => 10,
		'pos_order' => 1,
		'pos_open' => 1,
		'pos_type' => 'enlisted'),
	array(
		'pos_name' => 'Marine',
		'pos_desc' => "The UEO Marine Corps represents some of the most skilled combat ground forces in the world. Training to be a UEO Marine is intense with the singular goal of being a deterrent peace-keeping force.",
		'pos_dept' => 10,
		'pos_order' => 2,
		'pos_open' => 30,
		'pos_type' => 'enlisted'),
	array(
		'pos_name' => 'Support Supervisor',
		'pos_desc' => "UEO Support Survisors are civilian positions and are responsible for managing all crew support personnel stationed aboard UEO vessels.",
		'pos_dept' => 11,
		'pos_order' => 0,
		'pos_open' => 1,
		'pos_type' => 'senior'),
	array(
		'pos_name' => 'Cook',
		'pos_desc' => "Continuing the tradition from the US Navy, UEO cooks are some of the most skilled chefs in the world and often go on from their UEO service to cook in some of the most prestigious kitchens in the world. The cooks are responsible for stocking food supplies and preparing meals throughout the day.",
		'pos_dept' => 11,
		'pos_order' => 1,
		'pos_open' => 3,
		'pos_type' => 'other'),
	array(
		'pos_name' => 'Janitor',
		'pos_desc' => "Janitors are responsible for cleaning the vessel and general upkeep (changing light bulbs, minor repairs) that the Engineering department doesn't have the time or resources to deal with.",
		'pos_dept' => 11,
		'pos_order' => 2,
		'pos_open' => 2,
		'pos_type' => 'other'),
);

$catalogue_ranks = array(
	array(
		'rankcat_name' => 'Duty Uniform',
		'rankcat_location' => 'default',
		'rankcat_credits' => "The rank sets used in Nova were created by Anodyne Productions from the Beneath the Sea font. Please do not copy or modify the images.",
		'rankcat_default' => 'y',
		'rankcat_url' => 'http://xtras.anodyne-productions.com/',
		'rankcat_genre' => $g),
);