<?php

use Illuminate\Support\Collection;
use Nova\Foundation\Themes\Theme as BaseTheme;

class Theme extends BaseTheme {

	public $iconTemplate = '<i class="material-icons %2$s">%1$s</i>';

	public function iconMap(): array
	{
		return [
			'add'			=> 'add',
			'announcement'	=> 'mic',
			'archive'		=> 'archive',
			'arrow-back'	=> 'arrow_back',
			'arrow-down'	=> 'arrow_downward',
			'arrow-forward'	=> 'arrow_forward',
			'arrow-up'		=> 'arrow_upward',
			'ban'			=> 'block',
			'bolt'			=> 'flash_on',
			'book'			=> 'book',
			'bookmark'		=> 'bookmark',
			'briefcase'		=> 'work',
			'brush'			=> 'brush',
			'calendar'		=> 'event',
			'chart-area'	=> 'show_chart',
			'chart-bar'		=> 'insert_chart',
			'chart-line'	=> 'show_chart',
			'chart-pie'		=> 'pie_chart',
			'check'			=> 'check',
			'clock'			=> 'schedule',
			'close'			=> 'clear',
			'cloud'			=> 'cloud',
			'cloud-download'=> 'cloud_download',
			'cloud-upload'	=> 'cloud_upload',
			'code'			=> 'code',
			'comment'		=> 'chat_bubble',
			'comments'		=> 'forum',
			'copy'			=> 'content_copy',
			'cut'			=> 'content_cut',
			'dashboard'		=> 'dashboard',
			'delete'		=> 'delete',
			'desktop'		=> 'desktop_mac',
			'directions'	=> 'directions',
			'download'		=> 'file_download',
			'edit'			=> 'edit',
			'email'			=> 'email',
			'file'			=> 'insert_drive_file',
			'fire'			=> 'whatshot',
			'flag'			=> 'flag',
			'folder'		=> 'folder',
			'folder-open'	=> 'folder_open',
			'forward'		=> 'forward',
			'gift'			=> '',
			'heart'			=> 'favorite',
			'heart-empty'	=> 'favorite_border',
			'history'		=> 'history',
			'home'			=> 'home',
			'image'			=> 'image',
			'inbox'			=> 'inbox',
			'info'			=> 'info',
			'key'			=> 'vpn_key',
			'laptop'		=> 'laptop',
			'leaf'			=> 'nature',
			'light'			=> 'lightbulb_outline',
			'link'			=> 'link',
			'list'			=> 'list',
			'location'		=> 'location_on',
			'lock'			=> 'lock',
			'mobile'		=> 'smartphone',
			'more'			=> 'more_horiz',
			'not-visible'	=> 'visibility_off',
			'notifications'	=> 'notifications',
			'paste'			=> 'content_paste',
			'question'		=> 'help',
			'refresh'		=> 'autorenew',
			'reply'			=> 'reply',
			'reply-all'		=> 'reply_all',
			'search'		=> 'search',
			'send'			=> 'send',
			'settings'		=> 'settings',
			'share'			=> 'share',
			'shield'		=> '',
			'sign-in'		=> 'power_settings_new',
			'sign-out'		=> 'power_settings_new',
			'smile'			=> 'tag_faces',
			'star'			=> 'star',
			'star-empty'	=> 'star_border',
			'tablet'		=> 'tablet',
			'tag'			=> 'label',
			'tasks'			=> 'playlist_add_check',
			'thumbs-down'	=> 'thumb_down',
			'thumbs-up'		=> 'thumb_up',
			'ticket'		=> '',
			'trophy'		=> '',
			'unlock'		=> 'lock_open',
			'upload'		=> 'file_upload',
			'user'			=> 'person',
			'users'			=> 'people',
			'visible'		=> 'visibility',
			'warning'		=> 'warning',
			'wizard'		=> '',
			'wrench'		=> 'build',
		];
	}
}
