<?php

use Illuminate\Support\Collection;
use Nova\Foundation\Themes\Theme as BaseTheme;

class Theme extends BaseTheme {

	public $iconTemplate = '<i class="material-icons %2$s">%1$s</i>';

	public function iconMap(): array
	{
		return [
			'add'				=> 'add',
			'android'			=> 'android',
			'announcement'		=> 'mic',
			'apple'				=> '',
			'archive'			=> 'inbox',
			'arrow-down'		=> 'arrow_downward',
			'arrow-left'		=> 'arrow_back',
			'arrow-right'		=> 'arrow_forward',
			'arrow-up'			=> 'arrow_upward',
			'ban'				=> 'block',
			'bell'				=> 'notifications',
			'bell-outline'		=> 'notifications_none',
			'bolt'				=> 'flash_on',
			'book'				=> 'class',
			'bookmark'			=> 'turned_in',
			'briefcase'			=> 'business_center',
			'browser-chrome'	=> '',
			'browser-edge'		=> '',
			'browser-firefox'	=> '',
			'browser-ie'		=> '',
			'browser-safari'	=> '',
			'calendar'			=> 'insert_invitation',
			'caret-down'		=> 'arrow_drop_down',
			'caret-up'			=> 'arrow_drop_up',
			'chart-area'		=> 'bubble_chart',
			'chart-bar'			=> 'graphic_eq',
			'chart-line'		=> 'show_chart',
			'chart-pie'			=> 'pie_chart',
			'check'				=> 'done',
			'clock'				=> 'schedule',
			'clone'				=> 'queue',
			'close'				=> 'close',
			'cloud'				=> 'wb_cloudy',
			'cloud-download'	=> 'cloud_download',
			'cloud-upload'		=> 'cloud_upload',
			'code'				=> 'code',
			'comment'			=> 'chat_bubble',
			'comments'			=> 'question_answer',
			'dashboard'			=> 'dashboard',
			'delete'			=> 'delete',
			'device-desktop'	=> 'desktop_windows',
			'device-laptop'		=> 'laptop',
			'device-mobile'		=> 'phone_android',
			'device-tablet'		=> 'tablet_android',
			'download'			=> 'vertical_align_bottom',
			'edit'				=> 'more_edit',
			'email'				=> 'drafts',
			'hide'				=> 'visibility_off',
			'face-frown'		=> 'sentiment_dissatisfied',
			'face-meh'			=> 'sentiment_neutral',
			'face-smile'		=> 'sentiment_satisfied',
			'facebook'			=> '',
			'file'				=> 'insert_drive_file',
			'file-text'			=> 'insert_drive_file',
			'fire'				=> 'whatshot',
			'flag'				=> 'flag',
			'folder'			=> 'folder',
			'folder-open'		=> 'folder_open',
			'forward'			=> '',
			'gift'				=> '',
			'google'			=> '',
			'heart'				=> 'favorite',
			'heart-empty'		=> 'favorite_border',
			'history'			=> 'restore',
			'home'				=> 'home',
			'image'				=> 'photo_size_select_actual',
			'inbox'				=> 'inbox',
			'info'				=> 'info',
			'key'				=> 'vpn_key',
			'leaf'				=> 'nature',
			'lightbulb'			=> 'lightbulb_outline',
			'link'				=> 'link',
			'linux'				=> '',
			'list'				=> 'format_list_bulleted',
			'lock'				=> 'lock_outline',
			'magic'				=> 'phonelink_setup',
			'map-marker'		=> 'pin_drop',
			'map-signs'			=> 'directions',
			'more-horizontal'	=> 'more_horiz',
			'more-vertical'		=> 'more_vert',
			'paint-brush'		=> 'brush',
			'paper-plane'		=> 'send',
			'paper-plane-alt'	=> 'send',
			'question'			=> 'help',
			'refresh'			=> 'cached',
			'reply'				=> 'reply',
			'reply-all'			=> 'reply_all',
			'search'			=> 'search',
			'share'				=> 'share',
			'shield'			=> 'verified_user',
			'setting'			=> 'settings',
			'settings'			=> 'settings',
			'settings-alt'		=> 'settings_applications',
			'show'				=> 'visibility',
			'sign-in'			=> '',
			'sign-out'			=> 'exit_to_app',
			'sort-alpha-asc'	=> 'sort_by_alpha',
			'sort-alpha-desc'	=> 'sort_by_alpha',
			'sort-amount-asc'	=> 'sort',
			'sort-amount-desc'	=> 'sort',
			'sort-numeric-asc'	=> 'sort',
			'sort-numeric-desc'	=> 'sort',
			'star'				=> 'star',
			'star-empty'		=> 'star_border',
			'support'			=> 'help',
			'tag'				=> 'local_offer',
			'tags'				=> 'local_offer',
			'tasks'				=> 'assignment_turned_in',
			'thumbs-down'		=> 'thumb_down',
			'thumbs-up'			=> 'thumb_up',
			'ticket'			=> 'local_play',
			'trophy'			=> '',
			'twitter'			=> '',
			'unlock'			=> 'lock_open',
			'upload'			=> 'file_upload',
			'user'				=> 'person',
			'user-card'			=> 'contact_mail',
			'user-circle'		=> 'account_circle',
			'users'				=> 'people',
			'warning'			=> 'warning',
			'windows'			=> '',
			'wrench'			=> 'build',
		];
	}
}
