export default [
    {
        id: 'step-nav-search',
        title: 'Global search',
        text: 'Quickly locate announcements, characters, posts, or stories from anywhere in Nova using global search.',
        attachTo: { element: '[data-tour=dashboard-search]', on: 'right' },
        buttons: [{ text: 'Next', action: () => window.TourManager.instances['dashboard-tour'].next() }],
    },
    {
        id: 'step-nav-messages',
        title: 'Private messages',
        text: 'Send and receive direct messages with other users — individually or in groups — without leaving Nova.',
        attachTo: { element: '[data-tour=dashboard-messages]', on: 'right' },
        buttons: [{ text: 'Next', action: () => window.TourManager.instances['dashboard-tour'].next() }],
    },
    {
        id: 'step-nav-notifications',
        title: 'In-app notifications',
        text: 'Stay updated with system and player activity through Nova’s built-in notification system — no email clutter required.',
        attachTo: { element: '[data-tour=dashboard-notifications]', on: 'right' },
        buttons: [{ text: 'Next', action: () => window.TourManager.instances['dashboard-tour'].next() }],
    },
    {
        id: 'step-nav-writing',
        title: 'Writing tools',
        text: 'Everyone can write story posts, but managing post types and organizing story arcs may require additional permissions.',
        attachTo: { element: '[data-tour=writing]', on: 'right' },
        buttons: [{ text: 'Next', action: () => window.TourManager.instances['dashboard-tour'].next() }],
    },
    {
        id: 'step-nav-characters',
        title: 'Character management',
        text: 'Manage all characters in the game, including their roles, ranks, departments, and more.',
        attachTo: { element: '[data-tour=characters]', on: 'right' },
        buttons: [{ text: 'Next', action: () => window.TourManager.instances['dashboard-tour'].next() }],
    },
    {
        id: 'step-nav-users',
        title: 'User administration',
        text: 'Invite players, assign roles, and manage access to different parts of the game’s backend here.',
        attachTo: { element: '[data-tour=users]', on: 'right' },
        buttons: [{ text: 'Next', action: () => window.TourManager.instances['dashboard-tour'].next() }],
    },
    {
        id: 'step-nav-pages',
        title: 'Page manager',
        text: 'Create, edit, and organize public-facing pages using a flexible block-based editor — perfect for customizing your site’s content.',
        attachTo: { element: '[data-tour=pages]', on: 'right' },
        buttons: [{ text: 'Next', action: () => window.TourManager.instances['dashboard-tour'].next() }],
    },
    {
        id: 'step-nav-forms',
        title: 'Form manager',
        text: 'Design and manage custom forms for user submissions, applications, and game interaction using Nova’s block editor.',
        attachTo: { element: '[data-tour=forms]', on: 'right' },
        buttons: [{ text: 'Next', action: () => window.TourManager.instances['dashboard-tour'].next() }],
    },
    {
        id: 'step-nav-reporting',
        title: 'Reports',
        text: 'Access various reports to gain insights into writing activity, character stats, player engagement, and more.',
        attachTo: { element: '[data-tour=reporting]', on: 'right' },
        buttons: [{ text: 'Next', action: () => window.TourManager.instances['dashboard-tour'].next() }],
    },
    {
        id: 'step-nav-settings',
        title: 'Settings',
        text: 'Configure core settings that define how Nova behaves — from appearance and behavior to system defaults.',
        attachTo: { element: '[data-tour=settings]', on: 'right' },
        buttons: [{ text: 'Next', action: () => window.TourManager.instances['dashboard-tour'].next() }],
    },
    {
        id: 'step-nav-system',
        title: 'System overview',
        text: 'Monitor the system, manage add-ons, edit navigation, customize themes, and check logs — all in one place.',
        attachTo: { element: '[data-tour=system]', on: 'right' },
        buttons: [{ text: 'Next', action: () => window.TourManager.instances['dashboard-tour'].next() }],
    },
    {
        id: 'step-writing-overview',
        title: 'Contribution overview',
        text: 'Get a snapshot of recent writing activity from all players, including post counts and timelines.',
        attachTo: { element: '[data-tour=dashboard-writing-overview]', on: 'left' },
        buttons: [{ text: 'Next', action: () => window.TourManager.instances['dashboard-tour'].next() }],
    },
    {
        id: 'step-writing-level',
        title: 'Contribution level',
        text: 'Track your overall contributions to the game and see how your efforts stack up — a gamified way to encourage writing.',
        attachTo: { element: '[data-tour=dashboard-writing-level]', on: 'left' },
        buttons: [{ text: 'Next', action: () => window.TourManager.instances['dashboard-tour'].next() }],
    },
    {
        id: 'step-writing-stats',
        title: 'Personal stats',
        text: 'View your own writing trends and metrics, including word count, post frequency, and character usage.',
        attachTo: { element: '[data-tour=dashboard-writing-stats]', on: 'left' },
        buttons: [{ text: 'Next', action: () => window.TourManager.instances['dashboard-tour'].next() }],
    },
    {
        id: 'step-help',
        title: 'Need help?',
        text: 'Join our Discord server to get support, ask questions, or get help building and customizing your Nova game.',
        attachTo: { element: '[data-tour=dashboard-help]', on: 'right' },
        buttons: [
            { text: 'Back', action: () => window.TourManager.instances['dashboard-tour'].back() },
            {
                text: 'Finish',
                action: () => {
                    window.TourManager.instances['dashboard-tour'].complete();
                },
            },
        ],
    },
];
