<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Nova\Stories\Models\Story;

class KhitomerStorySeeder extends Seeder
{
    public function run(): void
    {
        activity()->disableLogging();

        $season1 = Story::factory()->completed()->create(['title' => 'Season 1', 'order_column' => 1]);
        $season2 = Story::factory()->completed()->create(['title' => 'Season 2', 'order_column' => 2]);
        $season3 = Story::factory()->ongoing()->create(['title' => 'Season 3', 'order_column' => 3]);

        Story::factory()->completed()->create(['title' => 'Remembrance', 'description' => 'At the end of the 24th Century, and 14 years after his retirement from Starfleet, Jean-Luc Picard is living a quiet life on his vineyard, Chateau Picard. When he is sought out by a mysterious young woman, Dahj, in need of his help, he soon realizes she may have personal connections to his own past.', 'parent_id' => $season1->id, 'order_column' => 1]);
        Story::factory()->completed()->create(['title' => 'Maps and Legends', 'description' => 'Picard begins investigating the mystery of Dahj as well as what her very existence means to the Federation. Without Starfleet’s support, Picard is left leaning on others for help, including Dr. Agnes Jurati and an estranged former colleague, Raffi Musiker. Meanwhile, hidden enemies are also interested in where Picard’s search for the truth about Dahj will lead.', 'parent_id' => $season1->id, 'order_column' => 2]);
        Story::factory()->completed()->create(['title' => 'The End Is the Beginning', 'description' => 'Completely unaware of her special nature, Soji continues her work and captures the attention of the Borg cube research project’s executive director. After rehashing past events with a reluctant Raffi, Picard seeks others willing to join his search for Bruce Maddox, including pilot and former Starfleet officer Cristóbal Rios.', 'parent_id' => $season1->id, 'order_column' => 3]);
        Story::factory()->completed()->create(['title' => 'Absolute Candor', 'description' => 'The crew’s journey to Freecloud takes a detour when Picard orders a stop at the planet Vashti, where Picard and Raffi relocated Romulan refugees 14 years earlier. Upon arrival, Picard reunites with Elnor, a young Romulan he befriended during the relocation. Meanwhile, Narek continues his attempts to learn more about Soji while Narissa’s impatience with his lack of progress grows.', 'parent_id' => $season1->id, 'order_column' => 4]);
        Story::factory()->completed()->create(['title' => 'Stardust City Rag', 'description' => 'The La Sirena crew begin an unpredictable and lively expedition on Freecloud to search for Bruce Maddox. When they learn Maddox has found himself in a precarious situation, a familiar face offers her assistance.', 'parent_id' => $season1->id, 'order_column' => 5]);
        Story::factory()->completed()->create(['title' => 'The Impossible Box', 'description' => 'Picard and the crew track Soji to the Borg cube in Romulan space, resurfacing haunting memories for Picard. Narek believes he has finally found a way to safely exploit Soji for information.', 'parent_id' => $season1->id, 'order_column' => 6]);
        Story::factory()->completed()->create(['title' => 'Nepenthe', 'description' => 'Picard and Soji transport to the planet Nepenthe, home to some old and trusted friends. As the rest of the La Sirena crew attempt to join them, Picard helps Soji make sense of her recently unlocked memories. Hugh and Elnor are left on the Borg cube and must face an angered Narissa.', 'parent_id' => $season1->id, 'order_column' => 7]);
        Story::factory()->completed()->create(['title' => 'Broken Pieces', 'description' => 'When devastating truths behind the Mars attack are revealed, Picard realizes just how far many will go to preserve secrets stretching back generations, all while the La Sirena crew grapples with secrets and revelations of their own. Narissa directs her guards to capture Elnor, setting off an unexpected chain of events on the Borg cube.', 'parent_id' => $season1->id, 'order_column' => 8]);
        Story::factory()->completed()->create(['title' => 'Et in Arcadia Ego, Part 1', 'description' => 'Following an unconventional and dangerous transit, Picard and the crew finally arrive at Soji’s home world, Coppelius. However, with Romulan warbirds on their tail, their arrival brings only greater danger as the crew discovers more than expected about the planet’s inhabitants.', 'parent_id' => $season1->id, 'order_column' => 9]);
        Story::factory()->completed()->create(['title' => 'Et in Arcadia Ego, Part 2', 'description' => 'A final confrontation on the synthetics’ homeworld Coppelius, pits Picard and his team against the Romulans, as well as the synths who seek to safeguard their existence at all costs.', 'parent_id' => $season1->id, 'order_column' => 10]);

        Story::factory()->completed()->create(['title' => 'The Star Gazer', 'description' => 'Starfleet must once again call on legendary Jean-Luc Picard after members of his former crew – Cristóbal Rios, Seven of Nine, Raffi Musiker, and Dr. Agnes Jurati – discover an anomaly in space that threatens the galaxy.', 'parent_id' => $season2->id, 'order_column' => 1]);
        Story::factory()->completed()->create(['title' => 'Penance', 'description' => 'Picard finds himself transported to an alternate timeline in the year 2400 where his longtime nemesis, Q, has orchestrated one final "trial." Picard searches for his trusted crew as he attempts to find the cause of this dystopian future.', 'parent_id' => $season2->id, 'order_column' => 2]);
        Story::factory()->completed()->create(['title' => 'Assimilation', 'description' => 'Picard and the crew travel back to 2024 Los Angeles in search of the "Watcher," who can help them identify the point at which time diverged. Seven, Raffi and Rios venture out into an unfamiliar world 400 years in their past, while Picard and Jurati attempt to gather information from an unlikely, and dangerous, ally.', 'parent_id' => $season2->id, 'order_column' => 3]);
        Story::factory()->completed()->create(['title' => 'Watcher', 'description' => 'With time running out to save the future, Picard takes matters into his own hands and seeks out an old friend for help. Meanwhile, Rios ends up on the wrong side of the law and Jurati makes a deal with the Borg Queen.', 'parent_id' => $season2->id, 'order_column' => 4]);
        Story::factory()->completed()->create(['title' => 'Fly Me to the Moon', 'description' => 'Picard discovers an important person from his past may be integral to the divergence in the timeline. Q continues his manipulation of the timeline, taking an interest in Dr. Adam Soong. Seven and Raffi attempt a daring rescue of Rios, while Jurati faces the consequences of her deal with the Borg Queen.', 'parent_id' => $season2->id, 'order_column' => 5]);
        Story::factory()->completed()->create(['title' => 'Two of One', 'description' => 'With the help of Tallinn, Picard and the crew infiltrate a gala on the eve of a joint space mission, to protect one of the astronauts they believe to be integral to the restoration of the timeline – Renee Picard. Kore makes a startling discovery about her father’s work.', 'parent_id' => $season2->id, 'order_column' => 6]);
        Story::factory()->completed()->create(['title' => 'Monsters', 'description' => 'Tallinn ventures inside Picard’s subconscious mind to help wake him from a coma and face both his darkest secrets and deepest fears. Seven and Raffi go in search of Jurati whom they fear has succumbed to the monster inside. Rios struggles to hide the truth of who he really is from Teresa.', 'parent_id' => $season2->id, 'order_column' => 7]);
        Story::factory()->completed()->create(['title' => 'Mercy', 'description' => 'With time running out before the launch of the Europa Mission, Picard and Guinan must free themselves from FBI custody. Seven and Raffi come face-to-face with Jurati and the horror of what she’s become.', 'parent_id' => $season2->id, 'order_column' => 8]);
        Story::factory()->completed()->create(['title' => 'Hide and Seek', 'description' => 'Picard and his crew fight for their lives as they come under attack from a new incarnation of an old enemy. But to survive, Picard must first face the ghosts of his past. Seven and Raffi have a final showdown with Jurati.', 'parent_id' => $season2->id, 'order_column' => 9]);
        Story::factory()->completed()->create(['title' => 'Farewell', 'description' => 'With just hours until the Europa Launch, Picard and the crew find themselves in a race against time to save the future.', 'parent_id' => $season2->id, 'order_column' => 10]);

        Story::factory()->completed()->create(['title' => 'The Next Generation', 'description' => 'After receiving a cryptic, urgent distress call from Dr. Beverly Crusher, Admiral Jean-Luc Picard enlists help from generations old and new to embark on one final adventure: a daring mission that will change Starfleet, and his old crew forever.', 'parent_id' => $season3->id, 'order_column' => 1]);
        Story::factory()->completed()->create(['title' => 'Disengage', 'description' => 'Aided by Seven of Nine and the crew of the U.S.S. Titan, Picard makes a shocking discovery that will alter his life forever -- and puts him on a collision course with the most cunning enemy he’s ever encountered. Meanwhile, Raffi races to track a catastrophic weapon -- and collides with a familiar ally.', 'parent_id' => $season3->id, 'order_column' => 2]);
        Story::factory()->completed()->create(['title' => 'Seventeen Seconds', 'description' => 'Picard grapples with an explosive, life-altering revelation, while the Titan and her crew try to outmaneuver a relentless Vadic in a lethal game of nautical cat and mouse. Meanwhile, Raffi and Worf uncover a nefarious plot from a vengeful enemy Starfleet has long since forgotten.', 'parent_id' => $season3->id, 'order_column' => 3]);
        Story::factory()->completed()->create(['title' => 'No Win Scenario', 'description' => 'With time running out, Picard, Riker and crew must confront the sins of their past and heal fresh wounds, while the Titan drifts helplessly toward certain destruction within a mysterious space anomaly.', 'parent_id' => $season3->id, 'order_column' => 4]);
        Story::factory()->completed()->create(['title' => 'Imposters', 'description' => 'Caught by Starfleet and facing court martial, paranoia grows as Picard struggles to uncover whether a prodigal crewman from his past has returned as an ally or an enemy hellbent on destroying them all.', 'parent_id' => $season3->id, 'order_column' => 5]);
        Story::factory()->completed()->create(['title' => 'The Bounty', 'description' => 'Now on the run, Picard and the skeleton crew of the U.S.S. Titan must break into Starfleet’s most top-secret facility to expose a plot that could destroy the Federation. Picard must turn to the only soul in the galaxy who can help – an old friend.', 'parent_id' => $season3->id, 'order_column' => 6]);
        Story::factory()->completed()->create(['title' => 'Dominion', 'description' => 'Crippled, cornered, and out of options, Picard stages a gambit to trap Vadic and reveal her true motive – a gamble that puts the Titan in the crosshairs and forces Picard and Beverly to question every moral code they’ve ever held.', 'parent_id' => $season3->id, 'order_column' => 7]);
        Story::factory()->completed()->create(['title' => 'Surrender', 'description' => 'Vadic forces Picard to make an impossible choice: deliver what he can never give… or watch his crew perish. Their only salvation lies in the mind of an old friend and old foe.', 'parent_id' => $season3->id, 'order_column' => 8]);
        Story::factory()->current()->create(['title' => 'Võx', 'description' => 'A devastating revelation about Jack alters the course of Picard’s life forever - and uncovers a truth that threatens every soul in the Federation. The final battle begins as Picard and his crew race to save the galaxy from annihilation.', 'parent_id' => $season3->id, 'order_column' => 9]);
        Story::factory()->upcoming()->create(['title' => 'The Last Generation', 'description' => 'In a desperate last stand, Jean-Luc Picard & generations of crews both old & new fight together to save the galaxy from the greatest threat they’ve ever faced as the saga of The Next Generation comes to a thrilling, epic conclusion.', 'parent_id' => $season3->id, 'order_column' => 10]);

        activity()->enableLogging();
    }
}
