<?php

return [

	'departments' => [
		[
			'name' => 'Command',
			'description' => "The Command department is ultimately responsible for the ship and its crew, and those within the department are responsible for commanding the vessel and representing the interests of Starfleet.",
			'order' => 0,
			'positions' => [
				[
					'name' => 'Commanding Officer',
					'description' => "Ultimately responsible for the ship and crew, the Commanding Officer is the most senior officer aboard a vessel. S/he is responsible for carrying out the orders of Starfleet, and for representing both Starfleet and the Federation.",
					'order' => 0,
					'available' => 1,
				],
				[
					'name' => 'Executive Officer',
					'description' => "The liaison between captain and crew, the Executive Officer acts as the disciplinarian, personnel manager, advisor to the captain, and much more. S/he is also one of only two officers, along with the Chief Medical Officer, that can remove a Commanding Officer from duty.",
					'order' => 1,
					'available' => 1,
				],
				[
					'name' => 'Chief of the Boat',
					'description' => "The senior-most Chief Petty Officer (including Senior and Master Chiefs), regardless of rating, is designated by the Commanding Officer as the Chief of the Boat (for vessels) or Command Chief (for starbases). In addition to his or her departmental responsibilities, the COB/CC performs the following duties: serves as a liaison between the Commanding Officer (or Executive Officer) and the enlisted crewmen; ensures enlisted crews understand Command policies; advises the Commanding Officer and Executive Officer regarding enlisted morale, and evaluates the quality of noncommissioned officer leadership, management, and supervisory training.\r\n\r\nThe COB/CC works with the other department heads, Chiefs, supervisors, and crewmen to insure discipline is equitably maintained, and the welfare, morale, and health needs of the enlisted personnel are met. The COB/CC is qualified to temporarily act as Commanding or Executive Officer if so ordered.",
					'order' => 2,
					'available' => 1,
				],
			],
		],
		[
			'name' => 'Helm',
			'description' => "Responsible for the navigation and flight control of a vessel and its auxiliary craft, the Helm division includes pilots trained in both starship and auxiliary craft piloting.",
			'order' => 1,
			'positions' => [
				[
					'name' => 'Chief Helm Officer',
					'description' => "Helm incorporates two job, Navigation and flight control. A Helm Officer must always be present on the bridge of a starship. S/he plots courses, supervises the computers piloting, corrects any flight deviations and pilots the ship manually when needed. The Chief Helm Officer is the senior most Helm Officer aboard, serving as a Senior Officer, and chief of the personnel under him/her.",
					'order' => 0,
					'available' => 1,
				],
				[
					'name' => 'Helm Officer',
					'description' => "Helm incorporates two job, Navigation and flight control. A Helm Officer must always be present on the bridge of a starship, and every vessel has a number of Helm Officers to allow shift rotations. S/he plots courses, supervises the computers piloting, corrects any flight deviations and pilots the ship manually when needed. Helm Officers report to the Chief Helm Officer.",
					'order' => 1,
					'available' => 5,
				],
			],
		],
		[
			'name' => 'Armory',
			'description' => "Merging the responsibilities of ship to ship and personnel combat into a single department, the armory division is responsible for the tactical readiness of the vessel and the security of the ship.",
			'order' => 2,
			'positions' => [
				[
					'name' => 'Chief Armory Officer',
					'description' => "Her/his duty is to ensure the safety of ship and crew. Some take it as their personal duty to protect the Commanding Officer/Executive Officer on away teams. She/he is also responsible for people under arrest and the safety of guests, liked or not. S/he also is a department head and a member of the senior staff, responsible for all the crew members in her/his department and duty rosters.",
					'order' => 0,
					'available' => 1,
				],
				[
					'name' => 'Armory Officer',
					'description' => "There are several Armory Officers aboard each vessel. They are assigned to their duties by the Armory Chief and mostly guard sensitive areas, protect people, patrol, and handle other threats to the Federation.",
					'order' => 1,
					'available' => 5,
				],
				[
					'name' => 'Security Investigations Officer',
					'description' => "The Security Investigations Officer is an Enlisted Officer. S/He fulfills the role of a special investigator or detective when dealing with Starfleet matters aboard ship or on a planet. Coordinates with the Chief Armory Officer on all investigations as needed. The Security Investigations Officer reports to the Chief Armory Officer.",
					'order' => 5,
					'available' => 2,
				],
				[
					'name' => 'Brig Officer',
					'description' => "The Brig Officer is an Armory Officer who has chosen to specialize in a specific role. S/he guards the brig and its cells. But there are other duties associated with this post as well. S/he is responsible for any prisoner transport, and the questioning of prisoners.",
					'order' => 10,
					'available' => 5,
				],
				[
					'name' => 'Master-at-Arms',
					'description' => "The Master-at-Arms trains and supervises Armory crewmen in departmental operations, repairs, and protocols; maintains duty assignments for all Armory personnel; supervises weapons locker access and firearm deployment; and is qualified to temporarily act as Chief Armory Officer if so ordered. The Master-at-Arms reports to the Chief Armory Officer.",
					'order' => 15,
					'available' => 1,
				],
			],
		],
		[
			'name' => 'Engineering',
			'description' => "The engineering division has the enormous task of keeping the ship working; they are responsible for making repairs, fixing problems, and making sure that the ship is ready for anything.",
			'order' => 3,
			'positions' => [
				[
					'name' => 'Chief Engineer',
					'description' => "The Chief Engineer is responsible for the condition of all systems and equipment on board a Starfleet ship or facility. S/he oversees maintenance, repairs and upgrades of all equipment. S/he is also responsible for the many repairs teams during crisis situations.\r\n\r\nThe Chief Engineer is not only the department head but also a senior officer, responsible for all the crew members in her/his department and maintenance of the duty rosters.",
					'order' => 0,
					'available' => 1,
				],
				[
					'name' => 'Assistant Chief Engineer',
					'description' => "The Assistant Chief Engineer assists the Chief Engineer in the daily work; in issues regarding mechanical, administrative matters and co-ordinating repairs with other departments.\r\n\r\nIf so required, the Assistant Chief Engineer must be able to take over as Chief Engineer, and thus must be versed in current information regarding the ship or facility.",
					'order' => 1,
					'available' => 1,
				],
				[
					'name' => 'Engineer',
					'description' => "There are several non-specialized engineers aboard of each vessel. They are assigned to their duties by the Chief Engineer and his Assistant, performing a number of different tasks as required, i.e. general maintenance and repair. Generally, engineers as assigned to more specialized engineering person to assist in there work is so requested by the specialized engineer.",
					'order' => 5,
					'available' => 10,
				],
				[
					'name' => 'Damage Control Specialist',
					'description' => "The Damage Control Specialist is a specialized Engineer. The Damage Control Specialist controls all damage control aboard the ship when it gets damaged in battle. S/he oversees all damage repair aboard the ship, and coordinates repair teams on the smaller jobs so the Chief Engineer can worry about other matters.\r\n\r\nA small team is assigned to the Damage Control Specialist which is made up from NCO personnel assigned by the Assistant and Chief Engineer. The Damage Control Specialist reports to the Assistant and Chief Engineer.",
					'order' => 10,
					'available' => 5,
				],
			],
		],
		[
			'name' => 'Science',
			'description' => "From sensor readings to figuring out a way to enter the strange spacial anomaly, the science division is responsible for recording data, testing new ideas out, and making discoveries.",
			'order' => 4,
			'positions' => [
				[
					'name' => 'Chief Science Officer',
					'description' => "The Chief Science Officer is responsible for all the scientific data the ship/facility collects, and the distribution of such data to specific section within the department for analysis. S/he is also responsible with providing the ship's captain with scientific information needed for command decisions.\r\n\r\nS/he also is a department head and a member of the Senior Staff and responsible for all the crew members in her/his department and duty rosters.",
					'order' => 0,
					'available' => 1,
				],
				[
					'name' => 'Science Officer',
					'description' => "There are several general Science Officers aboard each vessel. They are assigned to their duties by the Chief Science Officer and his Assistant. Assignments include work for the Specialized Section heads, as well as duties for work being carried out by the Chief.",
					'order' => 5,
					'available' => 5,
				],
			],
		],
		[
			'name' => 'Medical',
			'description' => "The medical division is responsible for the mental and physical health of the crew, from running annual physicals to combatting a strange plague that is afflicting the crew to helping a crew member deal with the loss of a loved one.",
			'order' => 5,
			'positions' => [
				[
					'name' => 'Chief Medical Officer',
					'description' => "The Chief Medical Officer is responsible for the physical health of the entire crew, but does more than patch up injured crew members. His/her function is to ensure that they do not get sick or injured to begin with, and to this end monitors their health and conditioning with regular check ups. If necessary, the Chief Medical Officer can remove anyone from duty, even a Commanding Officer. Besides this s/he is available to provide medical advice to any individual who requests it.",
					'order' => 0,
					'available' => 1,
				],
				[
					'name' => 'Counselor',
					'description' => "Because of their training in psychology, technically the ship's/facility's Counselor is considered part of Starfleet Medical. The Counselor is responsible both for advising the Commanding Officer in dealing with other people and races, and in helping crew members with personal, psychological, and emotional problems.\r\n\r\nThe Counselor reports to the Chief Medical Officer.",
					'order' => 2,
					'available' => 1,
				],
				[
					'name' => 'Medical Officer',
					'description' => "Medical Officer undertake the majority of the work aboard the ship/facility, examining the crew, and administering medical care under the instruction of the Chief Medical Officer.",
					'order' => 5,
					'available' => 5,
				],
				[
					'name' => 'Nurse',
					'description' => "Nurses are trained in basic medical care, and are capable of dealing with less serious medical cases. In more serious matters the nurse assist the medical officer in the examination and administration of medical care, be this injecting required drugs, or simply assuring the injured party that they will be ok. The Nurses also maintain the medical wards, overseeing the patients and ensuring they are receiving medication and care as instructed by the Medical Officer.",
					'order' => 10,
					'available' => 10,
				],
			],
		],
		[
			'name' => 'Communications',
			'description' => "The Communications department is responsible for the operation of the Starfleet's communications systems. On many ships the Communications department is simply amalgamated with Operations; it is often only on Flagships (where a large amount of communications traffic can be received in a very short space of time) and Starbases (where there is an extremely large amount of communications traffic at almost all times).",
			'order' => 6,
			'positions' => [
				[
					'name' => 'Chief Communications Officer',
					'description' => "Responsible for maintaining and upgrading the universal translator, controls the intercom and responsible for coordinating communications with other ships, stations or colonies/planets.",
					'order' => 0,
					'available' => 1,
				],
				[
					'name' => 'Communications Officer',
					'description' => "The Communications officer is responsible for managing all incoming and outgoing transmissions. This role involves the study of new and old languages and text in an attempt to better understand and interpret their meaning.",
					'order' => 5,
					'available' => 5,
				],
			],
		],
		[
			'name' => 'MACO Detachment',
			'description' => "When the standard security detail is not enough, MACOs come in and clean up; the MACO detachment is a powerful tactical addition to any ship, responsible for partaking in personal combat from sniping to melee.",
			'order' => 7,
			'positions' => [
				[
					'name' => 'MACO Commanding Officer',
					'description' => "The MACO Commanding Officer is responsible for all the MACO personnel assigned to the ship/facility. S/he is in required to take command of any special ground operations and lease such actions with security. The MACOs could be called the 23rd century commandos.\r\n\r\nThe CO can range from a Second Lieutenant on a small ship to a Lieutenant Colonel on a large facility or colony. Charged with the training, condition and tactical leadership of the MACO compliment, they are a member of the senior staff.\r\n\r\nAnswers to the Commanding Officer of the ship/facility.",
					'order' => 0,
					'available' => 1,
				],
				[
					'name' => 'MACO Executive Officer',
					'description' => "The Executive Officer of the MACOs, works like any Asst. Department head, removing some of the work load from the MACO CO and if the need arises taking on the role of MACO CO. S/he oversees the regular duties of the MACOs, from regular drills to equipment training, assignment and supply request to the ship/facilities Materials Officer.\r\n\r\nAnswers to the MACO Commanding Officer.",
					'order' => 1,
					'available' => 1,
				],
				[
					'name' => 'First Sergeant',
					'description' => "The First Sergeant is the highest ranked Enlisted MACO. S/He is in charge of all of the MACO enlisted affairs in the detachment. They assist the Company or Detachment Commander as their Executive Officer would. They act as a bridge, closing the gap between the NCO\'s and the Officers.\r\n\r\nAnswers To MACO Commanding Officer.",
					'order' => 5,
					'available' => 1,
				],
				[
					'name' => 'MACO',
					'description' => "Serving within a squad, the MACO is trained in a variety of means of combat, from melee to ranged projectile to sniping.",
					'order' => 10,
					'available' => 10,
				],
			],
		],
		[
			'name' => 'Civilians',
			'description' => "Civilians play an important role in Starfleet. Many civilian specialists across a number of fields work on occasion with Starfleet personnel as a Mission Specialist. In other cases, extra ship and station duties, such as running the ship's lounge, are outsourced to a civilian contract.",
			'order' => 8,
			'positions' => [
				[
					'name' => 'Chef',
					'description' => "Responsible for preparing all meals served in the Mess Hall and for the food during any diplomatic functions that may be held onboard.",
					'order' => 0,
					'available' => 1,
				],
			],
		],
	],

	'rankGroups' => [
		['name' => 'Admiralty', 'order' => 0],
		['name' => 'Command', 'order' => 1],
		['name' => 'Operations', 'order' => 2],
		['name' => 'Sciences', 'order' => 3],
		['name' => 'MACO', 'order' => 4],
	],

	'rankInfo' => [
		['name' => 'Admiral', 'short_name' => 'ADM', 'order' => 0],
		['name' => 'Vice Admiral', 'short_name' => 'VADM', 'order' => 1],
		['name' => 'Rear Admiral', 'short_name' => 'RADM', 'order' => 2],
		['name' => 'Commodore', 'short_name' => 'COMO', 'order' => 3],
		['name' => 'Captain', 'short_name' => 'CAPT', 'order' => 4],
		['name' => 'Commander', 'short_name' => 'CMDR', 'order' => 5],
		['name' => 'Lieutenant Commander', 'short_name' => 'LT CMDR', 'order' => 6],
		['name' => 'Lieutenant', 'short_name' => 'LT', 'order' => 7],
		['name' => 'Lieutenant (JG)', 'short_name' => 'LT JG', 'order' => 8],
		['name' => 'Ensign', 'short_name' => 'ENS', 'order' => 9],
		['name' => 'Master Chief Petty Officer', 'short_name' => 'MCPO', 'order' => 10],
		['name' => 'Senior Chief Petty Officer', 'short_name' => 'SCPO', 'order' => 11],
		['name' => 'Chief Petty Officer', 'short_name' => 'CPO', 'order' => 12],
		['name' => 'Petty Officer 1st Class', 'short_name' => 'PO1', 'order' => 13],
		['name' => 'Petty Officer 2nd Class', 'short_name' => 'PO2', 'order' => 14],
		['name' => 'Petty Officer 3rd Class', 'short_name' => 'PO3', 'order' => 15],
		['name' => 'Crewman 1st Class', 'short_name' => 'CR1', 'order' => 16],
		['name' => 'Crewman 2nd Class', 'short_name' => 'CR2', 'order' => 17],
		['name' => 'Crewman 3rd Class', 'short_name' => 'CR3', 'order' => 18],

		['name' => 'General', 'short_name' => 'GEN', 'order' => 20],
		['name' => 'Lieutenant General', 'short_name' => 'LT GEN', 'order' => 21],
		['name' => 'Major General', 'short_name' => 'MAJ GEN', 'order' => 22],
		['name' => 'Brigadier General', 'short_name' => 'BRG GEN', 'order' => 23],
		['name' => 'Colonel', 'short_name' => 'COL', 'order' => 24],
		['name' => 'Lieutenant Colonel', 'short_name' => 'LT COL', 'order' => 25],
		['name' => 'Major', 'short_name' => 'MAJ', 'order' => 26],
		['name' => 'Captain', 'short_name' => 'MCAPT', 'order' => 27],
		['name' => '1st Lieutenant', 'short_name' => '1LT', 'order' => 28],
		['name' => '2nd Lieutenant', 'short_name' => '2LT', 'order' => 29],
		['name' => 'Sergeant Major', 'short_name' => 'SGT MAJ', 'order' => 30],
		['name' => 'Master Sergeant', 'short_name' => 'MSGT', 'order' => 31],
		['name' => 'Gunnery Sergeant', 'short_name' => 'GSGT', 'order' => 32],
		['name' => 'Staff Sergeant', 'short_name' => 'SSGT', 'order' => 33],
		['name' => 'Sergeant', 'short_name' => 'SGT', 'order' => 34],
		['name' => 'Corporal', 'short_name' => 'CPL', 'order' => 35],
		['name' => 'Private 1st Class', 'short_name' => 'PVT1', 'order' => 36],
		['name' => 'Private E-2', 'short_name' => 'PVT E2', 'order' => 37],
		['name' => 'Private E-1', 'short_name' => 'PVT E1', 'order' => 38],
	],

	'ranks' => [
		['group_id' => 1, 'info_id' => 1, 'order' => 0, 'base' => 'flag/red.png', 'overlay' => 'starfleet/a4.png'],
		['group_id' => 1, 'info_id' => 2, 'order' => 1, 'base' => 'flag/red.png', 'overlay' => 'starfleet/a3.png'],
		['group_id' => 1, 'info_id' => 3, 'order' => 2, 'base' => 'flag/red.png', 'overlay' => 'starfleet/a2.png'],
		['group_id' => 1, 'info_id' => 4, 'order' => 3, 'base' => 'flag/red.png', 'overlay' => 'starfleet/a1.png'],
		['group_id' => 1, 'info_id' => 20, 'order' => 4, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/a4.png'],
		['group_id' => 1, 'info_id' => 21, 'order' => 5, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/a3.png'],
		['group_id' => 1, 'info_id' => 22, 'order' => 6, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/a2.png'],
		['group_id' => 1, 'info_id' => 23, 'order' => 7, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/a1.png'],

		['group_id' => 2, 'info_id' => 5, 'order' => 0, 'base' => 'officer/yellow.png', 'overlay' => 'starfleet/o6.png'],
		['group_id' => 2, 'info_id' => 6, 'order' => 1, 'base' => 'officer/yellow.png', 'overlay' => 'starfleet/o5.png'],
		['group_id' => 2, 'info_id' => 7, 'order' => 2, 'base' => 'officer/yellow.png', 'overlay' => 'starfleet/o4.png'],
		['group_id' => 2, 'info_id' => 8, 'order' => 3, 'base' => 'officer/yellow.png', 'overlay' => 'starfleet/o3.png'],
		['group_id' => 2, 'info_id' => 9, 'order' => 4, 'base' => 'officer/yellow.png', 'overlay' => 'starfleet/o2.png'],
		['group_id' => 2, 'info_id' => 10, 'order' => 5, 'base' => 'officer/yellow.png', 'overlay' => 'starfleet/o1.png'],
		['group_id' => 2, 'info_id' => 11, 'order' => 6, 'base' => 'officer/yellow.png', 'overlay' => 'starfleet/e9.png'],
		['group_id' => 2, 'info_id' => 12, 'order' => 7, 'base' => 'officer/yellow.png', 'overlay' => 'starfleet/e8.png'],
		['group_id' => 2, 'info_id' => 13, 'order' => 8, 'base' => 'officer/yellow.png', 'overlay' => 'starfleet/e7.png'],
		['group_id' => 2, 'info_id' => 14, 'order' => 9, 'base' => 'officer/yellow.png', 'overlay' => 'starfleet/e6.png'],
		['group_id' => 2, 'info_id' => 15, 'order' => 10, 'base' => 'officer/yellow.png', 'overlay' => 'starfleet/e5.png'],
		['group_id' => 2, 'info_id' => 16, 'order' => 11, 'base' => 'officer/yellow.png', 'overlay' => 'starfleet/e4.png'],
		['group_id' => 2, 'info_id' => 17, 'order' => 12, 'base' => 'officer/yellow.png', 'overlay' => 'starfleet/e3.png'],
		['group_id' => 2, 'info_id' => 18, 'order' => 13, 'base' => 'officer/yellow.png', 'overlay' => 'starfleet/e2.png'],
		['group_id' => 2, 'info_id' => 19, 'order' => 14, 'base' => 'officer/yellow.png', 'overlay' => 'starfleet/e1.png'],

		['group_id' => 3, 'info_id' => 6, 'order' => 0, 'base' => 'officer/red.png', 'overlay' => 'starfleet/o5.png'],
		['group_id' => 3, 'info_id' => 7, 'order' => 1, 'base' => 'officer/red.png', 'overlay' => 'starfleet/o4.png'],
		['group_id' => 3, 'info_id' => 8, 'order' => 2, 'base' => 'officer/red.png', 'overlay' => 'starfleet/o3.png'],
		['group_id' => 3, 'info_id' => 9, 'order' => 3, 'base' => 'officer/red.png', 'overlay' => 'starfleet/o2.png'],
		['group_id' => 3, 'info_id' => 10, 'order' => 4, 'base' => 'officer/red.png', 'overlay' => 'starfleet/o1.png'],
		['group_id' => 3, 'info_id' => 11, 'order' => 5, 'base' => 'officer/red.png', 'overlay' => 'starfleet/e9.png'],
		['group_id' => 3, 'info_id' => 12, 'order' => 6, 'base' => 'officer/red.png', 'overlay' => 'starfleet/e8.png'],
		['group_id' => 3, 'info_id' => 13, 'order' => 7, 'base' => 'officer/red.png', 'overlay' => 'starfleet/e7.png'],
		['group_id' => 3, 'info_id' => 14, 'order' => 8, 'base' => 'officer/red.png', 'overlay' => 'starfleet/e6.png'],
		['group_id' => 3, 'info_id' => 15, 'order' => 9, 'base' => 'officer/red.png', 'overlay' => 'starfleet/e5.png'],
		['group_id' => 3, 'info_id' => 16, 'order' => 10, 'base' => 'officer/red.png', 'overlay' => 'starfleet/e4.png'],
		['group_id' => 3, 'info_id' => 17, 'order' => 11, 'base' => 'officer/red.png', 'overlay' => 'starfleet/e3.png'],
		['group_id' => 3, 'info_id' => 18, 'order' => 12, 'base' => 'officer/red.png', 'overlay' => 'starfleet/e2.png'],
		['group_id' => 3, 'info_id' => 19, 'order' => 13, 'base' => 'officer/red.png', 'overlay' => 'starfleet/e1.png'],

		['group_id' => 4, 'info_id' => 6, 'order' => 0, 'base' => 'officer/teal.png', 'overlay' => 'starfleet/o5.png'],
		['group_id' => 4, 'info_id' => 7, 'order' => 1, 'base' => 'officer/teal.png', 'overlay' => 'starfleet/o4.png'],
		['group_id' => 4, 'info_id' => 8, 'order' => 2, 'base' => 'officer/teal.png', 'overlay' => 'starfleet/o3.png'],
		['group_id' => 4, 'info_id' => 9, 'order' => 3, 'base' => 'officer/teal.png', 'overlay' => 'starfleet/o2.png'],
		['group_id' => 4, 'info_id' => 10, 'order' => 4, 'base' => 'officer/teal.png', 'overlay' => 'starfleet/o1.png'],
		['group_id' => 4, 'info_id' => 11, 'order' => 5, 'base' => 'officer/teal.png', 'overlay' => 'starfleet/e9.png'],
		['group_id' => 4, 'info_id' => 12, 'order' => 6, 'base' => 'officer/teal.png', 'overlay' => 'starfleet/e8.png'],
		['group_id' => 4, 'info_id' => 13, 'order' => 7, 'base' => 'officer/teal.png', 'overlay' => 'starfleet/e7.png'],
		['group_id' => 4, 'info_id' => 14, 'order' => 8, 'base' => 'officer/teal.png', 'overlay' => 'starfleet/e6.png'],
		['group_id' => 4, 'info_id' => 15, 'order' => 9, 'base' => 'officer/teal.png', 'overlay' => 'starfleet/e5.png'],
		['group_id' => 4, 'info_id' => 16, 'order' => 10, 'base' => 'officer/teal.png', 'overlay' => 'starfleet/e4.png'],
		['group_id' => 4, 'info_id' => 17, 'order' => 11, 'base' => 'officer/teal.png', 'overlay' => 'starfleet/e3.png'],
		['group_id' => 4, 'info_id' => 18, 'order' => 12, 'base' => 'officer/teal.png', 'overlay' => 'starfleet/e2.png'],
		['group_id' => 4, 'info_id' => 19, 'order' => 13, 'base' => 'officer/teal.png', 'overlay' => 'starfleet/e1.png'],

		['group_id' => 5, 'info_id' => 24, 'order' => 0, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/o6.png'],
		['group_id' => 5, 'info_id' => 25, 'order' => 1, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/o5.png'],
		['group_id' => 5, 'info_id' => 26, 'order' => 2, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/o4.png'],
		['group_id' => 5, 'info_id' => 27, 'order' => 3, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/o3.png'],
		['group_id' => 5, 'info_id' => 28, 'order' => 4, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/o2.png'],
		['group_id' => 5, 'info_id' => 29, 'order' => 5, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/o1.png'],
		['group_id' => 5, 'info_id' => 30, 'order' => 6, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/e9.png'],
		['group_id' => 5, 'info_id' => 31, 'order' => 7, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/e8.png'],
		['group_id' => 5, 'info_id' => 32, 'order' => 8, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/e7.png'],
		['group_id' => 5, 'info_id' => 33, 'order' => 9, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/e6.png'],
		['group_id' => 5, 'info_id' => 34, 'order' => 10, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/e5.png'],
		['group_id' => 5, 'info_id' => 35, 'order' => 11, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/e4.png'],
		['group_id' => 5, 'info_id' => 36, 'order' => 12, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/e3.png'],
		['group_id' => 5, 'info_id' => 37, 'order' => 13, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/e2.png'],
		['group_id' => 5, 'info_id' => 38, 'order' => 14, 'base' => 'officer/camouflage.png', 'overlay' => 'maco/e1.png'],
	],

];
