<?php

return [

	'departments' => [],

	'rankGroups' => [
		['name' => 'Air Force', 'order' => 0],
		['name' => 'Army', 'order' => 1],
		['name' => 'Marine Corps', 'order' => 2],
		['name' => 'Navy', 'order' => 3],
	],

	'rankInfo' => [
		['name' => 'General', 'short_name' => 'GEN', 'order' => 0],
		['name' => 'Lieutenant General', 'short_name' => 'LTG', 'order' => 1],
		['name' => 'Major General', 'short_name' => 'MG', 'order' => 2],
		['name' => 'Brigadier General', 'short_name' => 'BG', 'order' => 3],
		['name' => 'Colonel', 'short_name' => 'COL', 'order' => 4],
		['name' => 'Lieutenant Colonel', 'short_name' => 'LTC', 'order' => 5],
		['name' => 'Major', 'short_name' => 'MAJ', 'order' => 6],
		['name' => 'Captain', 'short_name' => 'CAPT', 'order' => 7],
		['name' => '1st Lieutenant', 'short_name' => '1LT', 'order' => 8],
		['name' => '2nd Lieutenant', 'short_name' => '2LT', 'order' => 9],
		['name' => 'Sergeant Major', 'short_name' => 'SGM', 'order' => 10],
		['name' => 'Command Sergeant Major', 'short_name' => 'CSM', 'order' => 10],
		['name' => 'Master Gunnery Sergeant', 'short_name' => 'MGSG', 'order' => 10],
		['name' => 'Chief Master Sergeant', 'short_name' => 'CMSG', 'order' => 10],
		['name' => 'Command Chief Master Sergeant', 'short_name' => 'CCMS', 'order' => 10],
		['name' => 'Master Sergeant', 'short_name' => 'MSG', 'order' => 11],
		['name' => '1st Sergeant', 'short_name' => '1SG', 'order' => 11],
		['name' => 'Senior Master Sergeant', 'short_name' => 'SMSG', 'order' => 11],
		['name' => 'Sergeant 1st Class', 'short_name' => 'SFC', 'order' => 12],
		['name' => 'Gunnery Sergeant', 'short_name' => 'GSG', 'order' => 12],
		['name' => 'Staff Sergeant', 'short_name' => 'SSG', 'order' => 13],
		['name' => 'Technical Sergeant', 'short_name' => 'TSG', 'order' => 13],
		['name' => 'Sergeant', 'short_name' => 'SGT', 'order' => 14],
		['name' => 'Corporal', 'short_name' => 'CPL', 'order' => 15],
		['name' => 'Specialist', 'short_name' => 'SPC', 'order' => 15],
		['name' => 'Senior Airman', 'short_name' => 'SRA', 'order' => 15],
		['name' => 'Private 1st Class', 'short_name' => 'PFC', 'order' => 16],
		['name' => 'Lance Corporal', 'short_name' => 'LCPL', 'order' => 16],
		['name' => 'Airman 1st Class', 'short_name' => 'A1C', 'order' => 16],
		['name' => 'Private E-2', 'short_name' => 'PV2', 'order' => 17],
		['name' => 'Airman', 'short_name' => 'AMN', 'order' => 17],
		
		['name' => 'Admiral', 'short_name' => 'ADM', 'order' => 18],
		['name' => 'Vice Admiral', 'short_name' => 'VADM', 'order' => 19],
		['name' => 'Rear Admiral Upper Half', 'short_name' => 'RADM', 'order' => 20],
		['name' => 'Rear Admiral Lower Half', 'short_name' => 'RADML', 'order' => 21],
		['name' => 'Captain', 'short_name' => 'CAPT', 'order' => 22],
		['name' => 'Commander', 'short_name' => 'CDR', 'order' => 23],
		['name' => 'Lieutenant Commander', 'short_name' => 'LCDR', 'order' => 24],
		['name' => 'Lieutenant', 'short_name' => 'LT', 'order' => 25],
		['name' => 'Lieutenant JG', 'short_name' => 'LTJG', 'order' => 26],
		['name' => 'Ensign', 'short_name' => 'ENS', 'order' => 27],
		['name' => 'Master Chief Petty Officer', 'short_name' => 'MCPO', 'order' => 28],
		['name' => 'Command Master Chief Petty Officer', 'short_name' => 'CMCPO', 'order' => 28],
		['name' => 'Senior Chief Petty Officer', 'short_name' => 'SCPO', 'order' => 29],
		['name' => 'Chief Petty Officer', 'short_name' => 'CPO', 'order' => 30],
		['name' => 'Petty Officer 1st Class', 'short_name' => 'PO1', 'order' => 31],
		['name' => 'Petty Officer 2nd Class', 'short_name' => 'PO2', 'order' => 32],
		['name' => 'Petty Officer 3rd Class', 'short_name' => 'PO3', 'order' => 33],
		['name' => 'Seaman', 'short_name' => 'SN', 'order' => 34],
		['name' => 'Seaman Apprentice', 'short_name' => 'SNA', 'order' => 35],
		['name' => 'Seaman Basic', 'short_name' => 'SNB', 'order' => 36],
	],

	'ranks' => [
		/**
		 * Air Force
		 */
		['group_id' => 1, 'info_id' => 1, 'order' => 0, 'base' => 'air_force/USAF-10.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 2, 'order' => 1, 'base' => 'air_force/USAF-09.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 3, 'order' => 2, 'base' => 'air_force/USAF-08.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 4, 'order' => 3, 'base' => 'air_force/USAF-07.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 5, 'order' => 4, 'base' => 'air_force/USAF-06.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 6, 'order' => 5, 'base' => 'air_force/USAF-05.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 7, 'order' => 6, 'base' => 'air_force/USAF-04.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 8, 'order' => 7, 'base' => 'air_force/USAF-03.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 9, 'order' => 8, 'base' => 'air_force/USAF-02.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 10, 'order' => 9, 'base' => 'air_force/USAF-01.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 14, 'order' => 10, 'base' => 'air_force/USAF-E9.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 17, 'order' => 10, 'base' => 'air_force/USAF-E9.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 15, 'order' => 10, 'base' => 'air_force/USAF-E9a.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 18, 'order' => 11, 'base' => 'air_force/USAF-E8.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 17, 'order' => 11, 'base' => 'air_force/USAF-E8.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 16, 'order' => 12, 'base' => 'air_force/USAF-E7.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 17, 'order' => 12, 'base' => 'air_force/USAF-E7.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 22, 'order' => 13, 'base' => 'air_force/USAF-E6.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 21, 'order' => 14, 'base' => 'air_force/USAF-E5.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 26, 'order' => 15, 'base' => 'air_force/USAF-E4.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 29, 'order' => 16, 'base' => 'air_force/USAF-E3.png', 'overlay' => null],
		['group_id' => 1, 'info_id' => 31, 'order' => 17, 'base' => 'air_force/USAF-E2.png', 'overlay' => null],

		/**
		 * Army
		 */
		['group_id' => 2, 'info_id' => 1, 'order' => 0, 'base' => 'army/o10.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 2, 'order' => 1, 'base' => 'army/o9.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 3, 'order' => 2, 'base' => 'army/o8.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 4, 'order' => 3, 'base' => 'army/o7.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 5, 'order' => 4, 'base' => 'army/o6.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 6, 'order' => 5, 'base' => 'army/o5.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 7, 'order' => 6, 'base' => 'army/o4.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 8, 'order' => 7, 'base' => 'army/o3.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 9, 'order' => 8, 'base' => 'army/o2.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 10, 'order' => 9, 'base' => 'army/o1.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 11, 'order' => 10, 'base' => 'army/e9.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 12, 'order' => 10, 'base' => 'army/e9a.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 16, 'order' => 11, 'base' => 'army/e8.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 17, 'order' => 11, 'base' => 'army/e8a.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 19, 'order' => 12, 'base' => 'army/e7.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 21, 'order' => 13, 'base' => 'army/e6.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 23, 'order' => 14, 'base' => 'army/e5.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 24, 'order' => 15, 'base' => 'army/e4.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 25, 'order' => 15, 'base' => 'army/e4a.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 27, 'order' => 16, 'base' => 'army/e3.jpg', 'overlay' => null],
		['group_id' => 2, 'info_id' => 30, 'order' => 17, 'base' => 'army/e2.jpg', 'overlay' => null],

		/**
		 * Marines Corps
		 */
		['group_id' => 3, 'info_id' => 1, 'order' => 0, 'base' => 'marines/o10.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 2, 'order' => 1, 'base' => 'marines/o9.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 3, 'order' => 2, 'base' => 'marines/o8.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 4, 'order' => 3, 'base' => 'marines/o7.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 5, 'order' => 4, 'base' => 'marines/o6.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 6, 'order' => 5, 'base' => 'marines/o5.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 7, 'order' => 6, 'base' => 'marines/o4.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 8, 'order' => 7, 'base' => 'marines/o3.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 9, 'order' => 8, 'base' => 'marines/o2.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 10, 'order' => 9, 'base' => 'marines/o1.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 11, 'order' => 10, 'base' => 'marines/e9.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 13, 'order' => 10, 'base' => 'marines/e9.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 16, 'order' => 11, 'base' => 'marines/e8.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 17, 'order' => 11, 'base' => 'marines/e8a.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 20, 'order' => 12, 'base' => 'marines/e7.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 21, 'order' => 13, 'base' => 'marines/e6.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 23, 'order' => 14, 'base' => 'marines/e5.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 24, 'order' => 15, 'base' => 'marines/e4.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 28, 'order' => 16, 'base' => 'marines/e3.jpg', 'overlay' => null],
		['group_id' => 3, 'info_id' => 27, 'order' => 17, 'base' => 'marines/e2.jpg', 'overlay' => null],

		/**
		 * Navy
		 */
		['group_id' => 4, 'info_id' => 32, 'order' => 0, 'base' => 'navy/UNS-C-010.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 33, 'order' => 1, 'base' => 'navy/UNS-C-09.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 34, 'order' => 2, 'base' => 'navy/UNS-C-08.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 35, 'order' => 3, 'base' => 'navy/UNS-C-07.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 36, 'order' => 4, 'base' => 'navy/UNS-C-06.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 37, 'order' => 5, 'base' => 'navy/UNS-C-05.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 38, 'order' => 6, 'base' => 'navy/UNS-C-04.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 39, 'order' => 7, 'base' => 'navy/UNS-C-03.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 40, 'order' => 8, 'base' => 'navy/UNS-C-02.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 41, 'order' => 9, 'base' => 'navy/UNS-C-01.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 42, 'order' => 10, 'base' => 'navy/UNS-E-09-B.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 43, 'order' => 10, 'base' => 'navy/UNS-E-09-A.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 44, 'order' => 11, 'base' => 'navy/UNS-E-08.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 45, 'order' => 12, 'base' => 'navy/UNS-E-07.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 46, 'order' => 13, 'base' => 'navy/UNS-E-06.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 47, 'order' => 14, 'base' => 'navy/UNS-E-05.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 48, 'order' => 15, 'base' => 'navy/UNS-E-04.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 49, 'order' => 16, 'base' => 'navy/UNS-E-03.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 50, 'order' => 17, 'base' => 'navy/UNS-E-02.png', 'overlay' => null],
		['group_id' => 4, 'info_id' => 51, 'order' => 18, 'base' => 'navy/UNS-E-01.png', 'overlay' => null],
	],

];
