on:
  push:
    branches:
      - "**"

name: Code Style
jobs:
  laravel-pint:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.5 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install Laravel Pint
        run: composer global require laravel/pint --no-interaction --no-progress

      - name: Check Coding Standards
        run: |
          "$(composer config --global bin-dir --absolute 2>/dev/null)/pint" --test
